package view_laporan;
import control.Control_barangKeluar;
import control.Control_detBarangKeluar;
import java.util.List;
import java.awt.Color;
import crud.trans_barangKeluar;
import crud.trans_detBarangKeluar;
import java.awt.Component;
import java.awt.Font;
import java.text.SimpleDateFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import model.model_barangKeluar;
import model.model_detail_barangKeluar;
import tableModel.tm_barangKeluar;
import tableModel.tm_detBarangKeluar;

public class laporan_barangKeluar extends javax.swing.JPanel {
    private Control_barangKeluar serviceKel = new trans_barangKeluar();
    private Control_detBarangKeluar serviceDet = new trans_detBarangKeluar();
    
    private tm_barangKeluar tblModelKel = new tm_barangKeluar();
    private tm_detBarangKeluar tblModelDet = new tm_detBarangKeluar();
    List<model_barangKeluar> list;
    
    public laporan_barangKeluar() {
        initComponents();
        tbl_barangKeluar.getTableHeader().setDefaultRenderer(new HeaderColor());
        tblDetail.getTableHeader().setDefaultRenderer(new HeaderColor());
        tbl_barangKeluar.setRowHeight(50);
        tblDetail.setRowHeight(50);
        tbl_barangKeluar.setModel(tblModelKel);
        tblDetail.setModel(tblModelDet);
        pn_detail.setVisible(false);
        jLabel11.setVisible(false);
        t_cari.setVisible(false);
        cbx_filter.setVisible(false);
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel3 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        dataBarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_barangKeluar = new javax.swing.JTable();
        t_cari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pn_detail = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDetail = new javax.swing.JTable();
        bt_closeDet = new javax.swing.JButton();
        jDateFrom = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jDateTo = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbx_filter = new javax.swing.JComboBox<>();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataBarang.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Laporan Barang Keluar");

        bt_submit.setBackground(new java.awt.Color(0, 11, 109));
        bt_submit.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_submit.setForeground(new java.awt.Color(255, 255, 255));
        bt_submit.setText("Submit");
        bt_submit.setBorderPainted(false);
        bt_submit.setPreferredSize(new java.awt.Dimension(90, 30));
        bt_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_submitActionPerformed(evt);
            }
        });

        tbl_barangKeluar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tbl_barangKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_barangKeluar.setGridColor(new java.awt.Color(204, 204, 204));
        tbl_barangKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_barangKeluarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_barangKeluar);

        t_cari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        t_cari.setForeground(new java.awt.Color(153, 153, 153));
        t_cari.setText("Cari");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_cariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_cariFocusLost(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_cariKeyReleased(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/magnifying-glass.png"))); // NOI18N

        pn_detail.setBackground(new java.awt.Color(0, 11, 109));
        pn_detail.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Detail Laporan");

        tblDetail.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetail.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(tblDetail);

        bt_closeDet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/closeMenu.png"))); // NOI18N
        bt_closeDet.setContentAreaFilled(false);
        bt_closeDet.setOpaque(true);
        bt_closeDet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_closeDetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_closeDetMouseExited(evt);
            }
        });
        bt_closeDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_closeDetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_detailLayout = new javax.swing.GroupLayout(pn_detail);
        pn_detail.setLayout(pn_detailLayout);
        pn_detailLayout.setHorizontalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_closeDet)
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pn_detailLayout.setVerticalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(bt_closeDet))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
        );

        jDateFrom.setBackground(new java.awt.Color(255, 255, 255));
        jDateFrom.setForeground(new java.awt.Color(0, 0, 0));
        jDateFrom.setDateFormatString("yyyy-MM-dd");
        jDateFrom.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jDateFrom.setPreferredSize(new java.awt.Dimension(90, 30));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Dari : ");

        jDateTo.setBackground(new java.awt.Color(255, 255, 255));
        jDateTo.setForeground(new java.awt.Color(0, 0, 0));
        jDateTo.setDateFormatString("yyyy-MM-dd");
        jDateTo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jDateTo.setPreferredSize(new java.awt.Dimension(90, 30));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Sampai :");

        txt_total.setBackground(new java.awt.Color(255, 255, 255));
        txt_total.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        txt_total.setForeground(new java.awt.Color(0, 0, 0));
        txt_total.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("TOTAL : ");

        cbx_filter.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbx_filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMUA", "TERJUAL", "RUSAK" }));
        cbx_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_filterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataBarangLayout = new javax.swing.GroupLayout(dataBarang);
        dataBarang.setLayout(dataBarangLayout);
        dataBarangLayout.setHorizontalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_submit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(pn_detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dataBarangLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dataBarangLayout.setVerticalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_submit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t_cari)
                        .addComponent(cbx_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(jDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(dataBarang, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_submitActionPerformed
         tampilkan(); 
    }//GEN-LAST:event_bt_submitActionPerformed

    private void tbl_barangKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_barangKeluarMouseClicked
          int row = tbl_barangKeluar.getSelectedRow();
          String id = tbl_barangKeluar.getValueAt(row, 0).toString();
          cbx_filter.setVisible(true);
          pn_detail.setVisible(true);
          bt_closeDet.setBackground(null);
          List<model_detail_barangKeluar> list = serviceDet.getData(id);
          tblModelDet.setData(list);
    }//GEN-LAST:event_tbl_barangKeluarMouseClicked

    private void t_cariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_cariFocusGained
        if(t_cari.getText().equalsIgnoreCase("Cari")) {
            t_cari.setText("");
            t_cari.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_t_cariFocusGained

    private void t_cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_cariFocusLost
        if(t_cari.getText().equalsIgnoreCase("")) {
            t_cari.setText("Cari");
        }
    }//GEN-LAST:event_t_cariFocusLost

    private void t_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyReleased

    }//GEN-LAST:event_t_cariKeyReleased

    private void bt_closeDetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_closeDetMouseEntered
        bt_closeDet.setBackground(Color.red);
    }//GEN-LAST:event_bt_closeDetMouseEntered

    private void bt_closeDetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_closeDetMouseExited
        bt_closeDet.setBackground(null);
    }//GEN-LAST:event_bt_closeDetMouseExited

    private void bt_closeDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_closeDetActionPerformed
        pn_detail.setVisible(false);
    }//GEN-LAST:event_bt_closeDetActionPerformed

    private void cbx_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_filterActionPerformed
        if(cbx_filter.getSelectedItem().equals("SEMUA")) {
            filterSemua();
        } else if(cbx_filter.getSelectedItem().equals("TERJUAL")) {
            filterTerjual();
        } else if(cbx_filter.getSelectedItem().equals("RUSAK")) {
            filterRusak();
        }
    }//GEN-LAST:event_cbx_filterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_closeDet;
    private javax.swing.JButton bt_submit;
    private javax.swing.JComboBox<String> cbx_filter;
    private javax.swing.JPanel dataBarang;
    private com.toedter.calendar.JDateChooser jDateFrom;
    private com.toedter.calendar.JDateChooser jDateTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_detail;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTable tblDetail;
    private javax.swing.JTable tbl_barangKeluar;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        List<model_barangKeluar> list = serviceKel.getData();
        tblModelKel.setData(list);
    }
    
    private void tampilkan() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String from = sdf.format(jDateFrom.getDate());
        String to = sdf.format(jDateTo.getDate());

        model_barangKeluar mk = new model_barangKeluar();
        model_barangKeluar mbk = new model_barangKeluar();
        Long subtotal = mk.getTotal_keluar();
        mk.setTgl_keluar(from);
        mbk.setTgl_keluar(to);
        mk.setTotal_keluar(subtotal);
        
        serviceKel.sumTotalReport(mk, mbk);
        txt_total.setText("Rp " + mk.getTotal_keluar().toString());
        list = serviceKel.cariSemua(from, to);
        tblModelKel.setData(list);
        pn_detail.setVisible(false);
    }
    
    private void filterSemua() {
        model_detail_barangKeluar mdbk = new model_detail_barangKeluar();
        model_barangKeluar mbk = new model_barangKeluar();
        
        int row = tbl_barangKeluar.getSelectedRow();
        mbk.setNo_keluar(tbl_barangKeluar.getModel().getValueAt(row, 0).toString());
        
        mdbk.setMod_barangKel_detKel(mbk);
        mdbk.setKeterangan("Semua");
        Long total = mdbk.getSubtotal_keluar();
        mdbk.setSubtotal_keluar(total);
        serviceDet.sumTotalSemua(mdbk);
        
        txt_total.setText("Rp " + mdbk.getSubtotal_keluar().toString());
        
        List<model_detail_barangKeluar> list = serviceDet.filterSemua(mdbk);
        tblModelDet.setData(list);
    }
    
    private void filterTerjual() {
        model_detail_barangKeluar mdbk = new model_detail_barangKeluar();
        model_barangKeluar mbk = new model_barangKeluar();
        
        int row = tbl_barangKeluar.getSelectedRow();
        mbk.setNo_keluar(tbl_barangKeluar.getModel().getValueAt(row, 0).toString());
        
        mdbk.setMod_barangKel_detKel(mbk);
        mdbk.setKeterangan("Terjual");
        Long total = mdbk.getSubtotal_keluar();
        mdbk.setSubtotal_keluar(total);
        serviceDet.sumTotalTerjual(mdbk);
        
        txt_total.setText("Rp " + mdbk.getSubtotal_keluar().toString());
        
        List<model_detail_barangKeluar> list = serviceDet.filterTerjual(mdbk);
        tblModelDet.setData(list);
    }
    
    private void filterRusak() {
        model_detail_barangKeluar mdbk = new model_detail_barangKeluar();
        model_barangKeluar mbk = new model_barangKeluar();
        
        int row = tbl_barangKeluar.getSelectedRow();
        mbk.setNo_keluar(tbl_barangKeluar.getModel().getValueAt(row, 0).toString());
        
        mdbk.setMod_barangKel_detKel(mbk);
        mdbk.setKeterangan("Rusak");
        Long total = mdbk.getSubtotal_keluar();
        mdbk.setSubtotal_keluar(total);
        serviceDet.sumTotalTerjual(mdbk);
        
        txt_total.setText("Rp " + mdbk.getSubtotal_keluar().toString());
        
        List<model_detail_barangKeluar> list = serviceDet.filterRusak(mdbk);
        tblModelDet.setData(list);
    }
    
    static public class HeaderColor extends DefaultTableCellRenderer{

        public HeaderColor() {
            setOpaque(true);
        }
        
        public Component getTableCellRendererComponent(JTable tbl_contoh, Object value, boolean selected, boolean focused, int row, int column) {
            super.getTableCellRendererComponent(tbl_contoh, value, selected, focused, row, column);
            setBackground(new Color(0,139,185,255));
            setForeground(new Color(255, 255, 255));
            setFont(new Font(null, Font.BOLD, 18));
            return this;
        }
    
    }
    
}
