package view_data;
import tableModel.tm_barang;
import crud.Crud_Barang;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import model.model_barang;
import model.model_jenisBarang;
import java.util.List;
import javax.swing.JOptionPane;
import control.Control_barang;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.JTableHeader;
import view_data.dialog_jenisBarang;

public class data_barang extends javax.swing.JPanel {
    private Control_barang service = new Crud_Barang();
    private tm_barang tblModel = new tm_barang();
    
    public data_barang() {
        initComponents();
        tblBarang.getTableHeader().setDefaultRenderer(new HeaderColor());
        tblBarang.setRowHeight(50);
        tblBarang.setModel(tblModel);
        cbxSatuan.setBackground(null);
        cbxSatuan.setForeground(null);
        
        loadData();
//        widhtColumn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        mainPanel = new javax.swing.JPanel();
        dataBarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_tambahData = new javax.swing.JButton();
        bt_hapusData = new javax.swing.JButton();
        bt_batalData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        t_cari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tambahBarang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bt_simpan = new javax.swing.JButton();
        bt_batal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t_namaJenis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t_jenisBarang = new javax.swing.JTextField();
        t_kodeBarang = new javax.swing.JTextField();
        t_namaBarang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxSatuan = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        t_harga = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bt_jenisBarang = new javax.swing.JButton();
        t_stok = new javax.swing.JTextField();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataBarang.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Data Barang");

        bt_tambahData.setBackground(new java.awt.Color(0, 11, 109));
        bt_tambahData.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_tambahData.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahData.setText("Tambah");
        bt_tambahData.setBorderPainted(false);
        bt_tambahData.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_tambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahDataActionPerformed(evt);
            }
        });

        bt_hapusData.setBackground(new java.awt.Color(255, 0, 0));
        bt_hapusData.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_hapusData.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusData.setText("Hapus");
        bt_hapusData.setBorderPainted(false);
        bt_hapusData.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_hapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusDataActionPerformed(evt);
            }
        });

        bt_batalData.setBackground(new java.awt.Color(255, 102, 0));
        bt_batalData.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_batalData.setForeground(new java.awt.Color(255, 255, 255));
        bt_batalData.setText("Batal");
        bt_batalData.setBorderPainted(false);
        bt_batalData.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_batalData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalDataActionPerformed(evt);
            }
        });

        tblBarang.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarang.setGridColor(new java.awt.Color(204, 204, 204));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        t_cari.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_cari.setForeground(new java.awt.Color(153, 153, 153));
        t_cari.setText("Cari");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_cari.setPreferredSize(new java.awt.Dimension(30, 20));
        t_cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_cariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_cariFocusLost(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_cariKeyReleased(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/magnifying-glass.png"))); // NOI18N

        javax.swing.GroupLayout dataBarangLayout = new javax.swing.GroupLayout(dataBarang);
        dataBarang.setLayout(dataBarangLayout);
        dataBarangLayout.setHorizontalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addComponent(bt_tambahData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_hapusData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_batalData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        dataBarangLayout.setVerticalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_tambahData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_hapusData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_batalData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1))
        );

        mainPanel.add(dataBarang, "card2");

        tambahBarang.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel3.setText("Tambah Data Barang");

        bt_simpan.setBackground(new java.awt.Color(0, 11, 109));
        bt_simpan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_simpan.setForeground(new java.awt.Color(255, 255, 255));
        bt_simpan.setText("Simpan");
        bt_simpan.setBorderPainted(false);
        bt_simpan.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpanActionPerformed(evt);
            }
        });

        bt_batal.setBackground(new java.awt.Color(252, 102, 0));
        bt_batal.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_batal.setForeground(new java.awt.Color(255, 255, 255));
        bt_batal.setText("Batal");
        bt_batal.setBorderPainted(false);
        bt_batal.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Kode Barang");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("No Jenis");

        t_namaJenis.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_namaJenis.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_namaJenis.setPreferredSize(new java.awt.Dimension(1, 30));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Nama Jenis");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Nama Barang");

        t_jenisBarang.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_jenisBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_jenisBarang.setPreferredSize(new java.awt.Dimension(1, 30));

        t_kodeBarang.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_kodeBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_kodeBarang.setPreferredSize(new java.awt.Dimension(1, 30));

        t_namaBarang.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_namaBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_namaBarang.setPreferredSize(new java.awt.Dimension(1, 30));
        t_namaBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_namaBarangKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Satuan");

        cbxSatuan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cbxSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jenis Satuan", "Pcs", "Pack", " ", " " }));
        cbxSatuan.setPreferredSize(new java.awt.Dimension(1, 30));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Harga");

        t_harga.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_harga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_harga.setPreferredSize(new java.awt.Dimension(1, 30));
        t_harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_hargaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_hargaKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Stok");

        bt_jenisBarang.setBackground(new java.awt.Color(0, 11, 109));
        bt_jenisBarang.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_jenisBarang.setForeground(new java.awt.Color(255, 255, 255));
        bt_jenisBarang.setText("Pilih");
        bt_jenisBarang.setBorderPainted(false);
        bt_jenisBarang.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_jenisBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_jenisBarangActionPerformed(evt);
            }
        });

        t_stok.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_stok.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_stok.setPreferredSize(new java.awt.Dimension(1, 30));
        t_stok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_stokKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_stokKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_namaJenis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_kodeBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_namaBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_harga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxSatuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(t_jenisBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_jenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3))
                    .addComponent(t_stok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_kodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_jenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_jenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(t_namaJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahBarangLayout = new javax.swing.GroupLayout(tambahBarang);
        tambahBarang.setLayout(tambahBarangLayout);
        tambahBarangLayout.setHorizontalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahBarangLayout.createSequentialGroup()
                        .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(tambahBarangLayout.createSequentialGroup()
                                .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 266, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tambahBarangLayout.setVerticalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(tambahBarang, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_hapusDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusDataActionPerformed
        hapusData();
        bt_tambahData.setText("Tambah");
    }//GEN-LAST:event_bt_hapusDataActionPerformed

    private void bt_batalDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalDataActionPerformed
        loadData();
        tampilPanel();
    }//GEN-LAST:event_bt_batalDataActionPerformed

    private void bt_tambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahDataActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(tambahBarang);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        t_kodeBarang.setText(service.nomor());
        t_kodeBarang.setEnabled(false);
        t_jenisBarang.setEnabled(false);
        t_namaJenis.setEnabled(false);
        
        if(bt_tambahData.getText().equalsIgnoreCase("Ubah")) {
            dataTable();
        }
        
    }//GEN-LAST:event_bt_tambahDataActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        loadData();
        tampilPanel();
        resetForm();
    }//GEN-LAST:event_bt_batalActionPerformed

    private void bt_jenisBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_jenisBarangActionPerformed
       boolean closlabel = true;
       dialog_jenisBarang djb = new dialog_jenisBarang(null, closlabel);
       djb.setVisible(true);
       
       t_jenisBarang.setText(djb.jenisBarang.getKode_jenis());
       t_namaJenis.setText(djb.jenisBarang.getNama_jenis());
       t_namaBarang.requestFocus();
       aktif();
    }//GEN-LAST:event_bt_jenisBarangActionPerformed

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        if(bt_tambahData.getText().equalsIgnoreCase("Tambah")) {
            bt_tambahData.setText("Ubah");
        }
        bt_hapusData.setVisible(true);
        bt_batalData.setVisible(true);
    }//GEN-LAST:event_tblBarangMouseClicked

    private void bt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpanActionPerformed
       if(bt_simpan.getText().equalsIgnoreCase("Simpan")) {
           simpanData();
       } else if(bt_simpan.getText().equals("Perbarui")) {
           perbaruiData();
       }
           
    }//GEN-LAST:event_bt_simpanActionPerformed

    private void t_stokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_stokKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bt_simpanActionPerformed(new ActionEvent(evt.getSource(), evt.getID(), "Key Press Simpan"));
        }
    }//GEN-LAST:event_t_stokKeyPressed

    private void t_namaBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_namaBarangKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_harga.requestFocus();
        }
    }//GEN-LAST:event_t_namaBarangKeyPressed

    private void t_hargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_hargaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_stok.requestFocus();
        }
    }//GEN-LAST:event_t_hargaKeyPressed

    private void t_cariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_cariFocusGained
        if(t_cari.getText().equalsIgnoreCase("Cari")) {
            t_cari.setText("");
            t_cari.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_t_cariFocusGained

    private void t_cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_cariFocusLost
        if(t_cari.getText().equalsIgnoreCase("")) {
            t_cari.setText("Cari");
        }
    }//GEN-LAST:event_t_cariFocusLost

    private void t_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyReleased
        pencarian();
    }//GEN-LAST:event_t_cariKeyReleased

    private void t_hargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_hargaKeyTyped
        char enter = evt.getKeyChar();
        if(Character.isDigit(enter) == false) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Masukkan hanya angka0-9", "Caution", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_t_hargaKeyTyped

    private void t_stokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_stokKeyTyped
       char enter = evt.getKeyChar();
       if(Character.isDigit(enter) == false) {
           evt.consume();
           JOptionPane.showMessageDialog(null, "Masukkan hanya angka0-9", "Caution", JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_t_stokKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_batalData;
    private javax.swing.JButton bt_hapusData;
    private javax.swing.JButton bt_jenisBarang;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JButton bt_tambahData;
    private javax.swing.JComboBox<String> cbxSatuan;
    private javax.swing.JPanel dataBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTextField t_harga;
    private javax.swing.JTextField t_jenisBarang;
    private javax.swing.JTextField t_kodeBarang;
    private javax.swing.JTextField t_namaBarang;
    private javax.swing.JTextField t_namaJenis;
    private javax.swing.JTextField t_stok;
    private javax.swing.JPanel tambahBarang;
    private javax.swing.JTable tblBarang;
    // End of variables declaration//GEN-END:variables

    private void dataTable() {
        dataBarang.setVisible(false);
        tambahBarang.setVisible(true);
        int row = tblBarang.getSelectedRow();
        jLabel3.setText("Perbarui Data Barang");
        t_kodeBarang.setEnabled(false);
        
        t_kodeBarang.setText(tblBarang.getModel().getValueAt(row, 0).toString());
        t_jenisBarang.setText(tblBarang.getModel().getValueAt(row, 1).toString());
        t_namaJenis.setText(tblBarang.getModel().getValueAt(row, 2).toString());
        t_namaBarang.setText(tblBarang.getModel().getValueAt(row, 3).toString());
        cbxSatuan.setSelectedItem(tblBarang.getModel().getValueAt(row, 4).toString());
        t_harga.setText(tblBarang.getModel().getValueAt(row, 5).toString());
        t_stok.setText(tblBarang.getModel().getValueAt(row, 6).toString());
        
        aktif();
        
        bt_simpan.setText("Perbarui");
        bt_batal.setVisible(true);
    }
    
    private void loadData() {
        bt_hapusData.setVisible(false);
        bt_batalData.setVisible(false);
        List<model_barang> list = service.getData();
        tblModel.setData(list);
    }
    
    private void widhtColumn() {
        TableColumn column;
        tblBarang.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = tblBarang.getColumnModel().getColumn(0);
        column.setPreferredWidth(40);
        column = tblBarang.getColumnModel().getColumn(1);
        column.setPreferredWidth(150);
        column = tblBarang.getColumnModel().getColumn(2);
        column.setPreferredWidth(150);
        column = tblBarang.getColumnModel().getColumn(3);
        column.setPreferredWidth(150);
        column = tblBarang.getColumnModel().getColumn(4);
        column.setPreferredWidth(150);
        column = tblBarang.getColumnModel().getColumn(5);
        column.setPreferredWidth(150);
        column = tblBarang.getColumnModel().getColumn(6);
        column.setPreferredWidth(150);
    }
    
    private void hapusData() {
        int index = tblBarang.getSelectedRow();
//        if(index != -1) {
            model_barang barang = new model_barang();
//            model_barang barang = tblModel.getData(tblBarang.convertRowIndexToModel(index));
            barang.setKode_barang(tblBarang.getModel().getValueAt(index, 0).toString());
            
            if(JOptionPane.showConfirmDialog(null, "Yakin data ingin dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                if(service.validasiHapus(barang) == true) {
                    
                service.hapusData(barang);
                tblModel.hapusData(index);
                loadData();
                resetForm();
                }
            }
//        } 
        else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu data dahulu yang akan dihapus");
        }
    }
    
    private void resetForm() {
        bt_simpan.requestFocus();
        bt_simpan.setText("Tambah");
        t_kodeBarang.setText("");
        t_jenisBarang.setText("");
        t_namaJenis.setText("");
        t_namaBarang.setText("");
        cbxSatuan.setSelectedItem(0);
        t_harga.setText("");
        t_stok.setText("");
        
    }
    
    private void tampilPanel() {
        mainPanel.removeAll();
        mainPanel.add(new data_barang());
        mainPanel.repaint();
        mainPanel.revalidate();
    }
    
    private void aktif() {
        t_namaBarang.setEnabled(true);
        cbxSatuan.setEnabled(true);
        t_harga.setEnabled(true);
        t_stok.setEnabled(true);
    }
    
    private void simpanData() {
        if(validasiInput() == true) {
            String kode_barang = t_kodeBarang.getText();
            String kode_jenis = t_jenisBarang.getText();
            String nama_jenisBarang = t_namaJenis.getText();
            String nama_barang = t_namaBarang.getText();
            String satuan = cbxSatuan.getSelectedItem().toString();
            Long harga = Long.parseLong(t_harga.getText());
            Integer stok = Integer.parseInt(t_stok.getText());
            
            model_barang barang = new model_barang();
            model_jenisBarang jenisBarang = new model_jenisBarang();
            
            barang.setKode_barang(kode_barang);
            jenisBarang.setKode_jenis(kode_jenis);
            jenisBarang.setNama_jenis(nama_jenisBarang);
            barang.setNama_barang(nama_barang);
            barang.setSatuan(satuan);
            barang.setHarga(harga);
            barang.setStok(stok);
            
            barang.setMod_jnsBarang(jenisBarang);
            
            service.tambahData(barang);
            tblModel.tambahData(barang);
            loadData();
            resetForm();
            tampilPanel();
            bt_simpan.setText("Tambah");
        }
    }
    
    private void perbaruiData() {
        int index = tblBarang.getSelectedRow();
//        if(index != -1) {
//            model_barang modbar = tblModel.getData(tblBarang.convertRowIndexToModel(index));
            if(validasiInput() == true) {
            String kode_barang = t_kodeBarang.getText();
            String kode_jenis = t_jenisBarang.getText();
            String nama_jenisBarang = t_namaJenis.getText();
            String nama_barang = t_namaBarang.getText();
            String satuan = cbxSatuan.getSelectedItem().toString();
            Long harga = Long.parseLong(t_harga.getText());
            Integer stok = Integer.parseInt(t_stok.getText());
            
            model_barang barang = new model_barang();
            model_jenisBarang jenisBarang = new model_jenisBarang();
            
            barang.setKode_barang(kode_barang);
            jenisBarang.setKode_jenis(kode_jenis);
            jenisBarang.setNama_jenis(nama_jenisBarang);
            barang.setNama_barang(nama_barang);
            barang.setSatuan(satuan);
            barang.setHarga(harga);
            barang.setStok(stok);
            
            barang.setMod_jnsBarang(jenisBarang);
            
            service.perbaruiData(barang);
            tblModel.perbaruiData(index, barang);
            loadData();
            resetForm();
            tampilPanel();
        }
//    }
}
    private void pencarian() {
        List<model_barang> list = service.pencarianData(t_cari.getText());
        tblModel.setData(list);
    }
    
    private boolean validasiInput() {
        boolean valid = false;
        if(t_jenisBarang.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode jenis barang tidak boleh kosong");
        } else if(t_namaJenis.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama jenis barang tidak boleh kosong");
        } else if(t_namaBarang.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama barang tidak boleh kosong");
        } else if(cbxSatuan.getSelectedItem().equals("Jenis Satuan")) {
            JOptionPane.showMessageDialog(null, "Satuan barang tidak boleh kosong");
        } else if(t_harga.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harga barang tidak boleh kosong");
        } else if(t_stok.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Stok barang tidak boleh kosong");
        } else {
            valid = true;
        }
        
        return valid;
    }
    
    static public class HeaderColor extends DefaultTableCellRenderer{

        public HeaderColor() {
            setOpaque(true);
        }
        
        public Component getTableCellRendererComponent(JTable tabel, Object value, boolean selected, boolean focused, int row, int column) {
            super.getTableCellRendererComponent(tabel, value, selected, focused, row, column);
            setBackground(new Color(0,139,185,255));
            setForeground(new Color(255, 255, 255));
            setFont(new Font(null, Font.BOLD, 18));
            return this;
        }
    
    }
    
}
