package view;
import control.Control_barangKeluar;
import control.Control_barangMasuk;
import control.Control_detBarangKeluar;
import control.Control_pemesanan;
import crud.trans_barangKeluar;
import crud.trans_barangMasuk;
import crud.trans_detBarangKeluar;
import crud.trans_pemesanan;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import model.model_barangKeluar;
import model.model_barangMasuk;
import model.model_detail_barangKeluar;
import model.model_pemesanan;
import tableModel.tm_barangMasuk;
import view_transaksi.transaksi_barangKeluar;
import view_transaksi.transaksi_barangMasuk;
import view_transaksi.transaksi_pemesanan;

public class beranda extends javax.swing.JPanel {
    private Control_pemesanan servicePem = new trans_pemesanan();
    private Control_detBarangKeluar serviceDet = new trans_detBarangKeluar();
    private Control_barangKeluar serviceKel = new trans_barangKeluar();
    private Control_barangMasuk serviceMas = new trans_barangMasuk();
    private tm_barangMasuk tblModelMas = new tm_barangMasuk();
    List<model_barangMasuk> list;
    
    public beranda(String date) {
        initComponents();
        jLabel2.setText(date);
        jLabel2.setVisible(false);
        jTable1.getTableHeader().setDefaultRenderer(new HeaderColor());
        jTable1.setRowHeight(50);
        jTable1.setModel(tblModelMas);
        list = serviceMas.getByDate(jLabel2.getText());
        tblModelMas.setData(list);
        
//      pemesanan
        model_pemesanan mp = new model_pemesanan();
        mp.setTgl_pesan(jLabel2.getText());
        servicePem.sumTotalContent(mp);
        
        
//      barang masuk
        model_barangMasuk mbm = new model_barangMasuk();
        mbm.setTgl_masuk(jLabel2.getText());
        serviceMas.sumTotalContent(mbm);
        
        
//      barang keluar
        model_barangKeluar mbk = new model_barangKeluar();
        mbk.setTgl_keluar(jLabel2.getText());
        serviceKel.sumTotalContent(mbk);
        bt_totalBarangKel.setText("Rp " + mbk.getTotal_keluar().toString());
        
//      barang terjual & rusak
        model_detail_barangKeluar mdbk = new model_detail_barangKeluar();
        model_detail_barangKeluar mdbkr = new model_detail_barangKeluar();
        mdbk.setMod_barangKel_detKel(mbk);
        mdbkr.setMod_barangKel_detKel(mbk);
        serviceDet.sumTotallBerandaTerjual(mdbk);
        serviceDet.sumTotallBerandaRusak(mdbkr);
        
        
        bt_totalPem.setText("Rp " + mp.getTotal_pesan().toString());
        bt_totalBarngMas.setText("Rp " + mbm.getTotal_masuk().toString());
        bt_terjual.setText("Rp " + mdbk.getSubtotal_keluar().toString());
        bt_rusak.setText("Rp " + mdbkr.getSubtotal_keluar().toString());
        

    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bt_totalPem = new javax.swing.JButton();
        bt_totalBarangKel = new javax.swing.JButton();
        bt_totalBarngMas = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_terjual = new javax.swing.JButton();
        bt_rusak = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        bt_totalPem.setBackground(new java.awt.Color(0, 0, 176));
        bt_totalPem.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bt_totalPem.setForeground(new java.awt.Color(255, 255, 255));
        bt_totalPem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checkout_bg.png"))); // NOI18N
        bt_totalPem.setText("Total Pemesanan");
        bt_totalPem.setBorder(null);
        bt_totalPem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_totalPem.setIconTextGap(20);
        bt_totalPem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_totalPem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_totalPemActionPerformed(evt);
            }
        });

        bt_totalBarangKel.setBackground(new java.awt.Color(178, 10, 0));
        bt_totalBarangKel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bt_totalBarangKel.setForeground(new java.awt.Color(255, 255, 255));
        bt_totalBarangKel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/in_bg.png"))); // NOI18N
        bt_totalBarangKel.setText("Total Barang Keluar");
        bt_totalBarangKel.setBorder(null);
        bt_totalBarangKel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_totalBarangKel.setIconTextGap(20);
        bt_totalBarangKel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_totalBarangKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_totalBarangKelActionPerformed(evt);
            }
        });

        bt_totalBarngMas.setBackground(new java.awt.Color(226, 128, 2));
        bt_totalBarngMas.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bt_totalBarngMas.setForeground(new java.awt.Color(255, 255, 255));
        bt_totalBarngMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/out_bg.png"))); // NOI18N
        bt_totalBarngMas.setText("Total Barang Masuk");
        bt_totalBarngMas.setToolTipText("");
        bt_totalBarngMas.setBorder(null);
        bt_totalBarngMas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_totalBarngMas.setIconTextGap(20);
        bt_totalBarngMas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_totalBarngMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_totalBarngMasActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 11, 109));

        jTable1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Barang Masuk Hari Ini\n");

        jLabel2.setText("Date");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1320, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Total Transaksi Hari ini");

        bt_terjual.setBackground(new java.awt.Color(0, 51, 51));
        bt_terjual.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bt_terjual.setForeground(new java.awt.Color(255, 255, 255));
        bt_terjual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/terjual.png"))); // NOI18N
        bt_terjual.setText("Total Barang Terjual");
        bt_terjual.setBorder(null);
        bt_terjual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_terjual.setIconTextGap(20);
        bt_terjual.setMaximumSize(new java.awt.Dimension(235, 114));
        bt_terjual.setMinimumSize(new java.awt.Dimension(235, 114));
        bt_terjual.setPreferredSize(new java.awt.Dimension(235, 114));
        bt_terjual.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        bt_rusak.setBackground(new java.awt.Color(51, 51, 0));
        bt_rusak.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        bt_rusak.setForeground(new java.awt.Color(255, 255, 255));
        bt_rusak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/broken.png"))); // NOI18N
        bt_rusak.setText("Total Barang Rusak");
        bt_rusak.setBorder(null);
        bt_rusak.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_rusak.setIconTextGap(20);
        bt_rusak.setMaximumSize(new java.awt.Dimension(235, 114));
        bt_rusak.setMinimumSize(new java.awt.Dimension(235, 114));
        bt_rusak.setPreferredSize(new java.awt.Dimension(235, 114));
        bt_rusak.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_totalPem, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_totalBarngMas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 216, Short.MAX_VALUE)
                        .addComponent(bt_totalBarangKel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 205, Short.MAX_VALUE)
                        .addComponent(bt_terjual, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_rusak, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bt_totalBarngMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_totalPem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_terjual, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_rusak, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_totalBarangKel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_totalPemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_totalPemActionPerformed
        jPanel1.removeAll();
        jPanel1.repaint();
        jPanel1.revalidate();
        
        jPanel1.add(new transaksi_pemesanan(""));
        jPanel1.repaint();
        jPanel1.revalidate();
        
    }//GEN-LAST:event_bt_totalPemActionPerformed

    private void bt_totalBarangKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_totalBarangKelActionPerformed
        jPanel1.removeAll();
        jPanel1.repaint();
        jPanel1.revalidate();
        
        jPanel1.add(new transaksi_barangKeluar(""));
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_bt_totalBarangKelActionPerformed

    private void bt_totalBarngMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_totalBarngMasActionPerformed
        jPanel1.removeAll();
        jPanel1.repaint();
        jPanel1.revalidate();
        
        jPanel1.add(new transaksi_barangMasuk(""));
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_bt_totalBarngMasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_rusak;
    private javax.swing.JButton bt_terjual;
    private javax.swing.JButton bt_totalBarangKel;
    private javax.swing.JButton bt_totalBarngMas;
    private javax.swing.JButton bt_totalPem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    static public class HeaderColor extends DefaultTableCellRenderer{

        public HeaderColor() {
            setOpaque(true);
        }
        
        public Component getTableCellRendererComponent(JTable tbl_contoh, Object value, boolean selected, boolean focused, int row, int column) {
            super.getTableCellRendererComponent(tbl_contoh, value, selected, focused, row, column);
            setBackground(new Color(0,139,185,255));
            setForeground(new Color(255, 255, 255));
            setFont(new Font(null, Font.BOLD, 18));
            return this;
        }
    
    }

}

