package view_transaksi;
import java.util.List;
import javax.swing.JOptionPane;
import java.awt.Color;
import control.Control_barangMasuk;
import control.Control_detBarangMasuk;
import control.Control_detPemesanan;
import crud.trans_barangMasuk;
import crud.trans_detBarangMasuk;
import crud.trans_detPemesanan;
import java.awt.Component;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import model.model_barangMasuk;
import model.model_detail_barangMasuk;
import model.model_detail_pemesanan;
import model.model_pemesanan;
import model.model_pengguna;
import model.model_supliyer;
import tableModel.tm_barangMasuk;
import tableModel.tm_detBarangMasuk;
import tableModel.tm_detPemesanan;


public class transaksi_barangMasuk extends javax.swing.JPanel {
    private Control_barangMasuk serviceMas = new trans_barangMasuk();
    private Control_detBarangMasuk serviceDet = new trans_detBarangMasuk();
    
    private tm_barangMasuk tblModelMas = new tm_barangMasuk();
    private tm_detBarangMasuk tblModelDet = new tm_detBarangMasuk();
    
//  Latihan otomatis
    private Control_detPemesanan serviceDetPem = new trans_detPemesanan();
    private tm_detPemesanan tblModelDetPem = new tm_detPemesanan();
    List<model_detail_pemesanan> list;
    
    public transaksi_barangMasuk(String id) {
        initComponents();
        lb_idUser.setText(id);
        tblBarangMas.getTableHeader().setDefaultRenderer(new HeaderColor());
        tblDetail.getTableHeader().setDefaultRenderer(new HeaderColor());
        tbl_detPem.getTableHeader().setDefaultRenderer(new HeaderColor());
        tblBarangMas.setRowHeight(50);
        tblDetail.setRowHeight(50);
        tbl_detPem.setRowHeight(50);
        tblBarangMas.setModel(tblModelMas);
        tblDetail.setModel(tblModelDet);
        
        tbl_detPem.setModel(tblModelDetPem);
        bt_cetak.setVisible(false);
        pn_detail.setVisible(false);
        
        loadData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel3 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        dataBarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_tambahData = new javax.swing.JButton();
        bt_hapusData = new javax.swing.JButton();
        bt_batalData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarangMas = new javax.swing.JTable();
        t_cari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pn_detail = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDetail = new javax.swing.JTable();
        bt_closeDet = new javax.swing.JButton();
        lb_idUser = new javax.swing.JLabel();
        bt_cetak = new javax.swing.JButton();
        latihan_otomatis = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bt_simpan1 = new javax.swing.JButton();
        bt_batal1 = new javax.swing.JButton();
        pn_barMasuk = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txt_tglMasuk = new javax.swing.JTextField();
        pn_inputPes = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        txt_noPesan = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_tglPesan = new javax.swing.JTextField();
        pil_pesanan = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        txt_totalPesan = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txt_idPeng = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txt_idSup = new javax.swing.JTextField();
        bt_submit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_namaSup = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_totalMas = new javax.swing.JTextField();
        jPane_detPem = new javax.swing.JScrollPane();
        tbl_detPem = new javax.swing.JTable();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataBarang.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Data Barang Masuk");

        bt_tambahData.setBackground(new java.awt.Color(0, 11, 109));
        bt_tambahData.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_tambahData.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahData.setText("Tambah");
        bt_tambahData.setBorderPainted(false);
        bt_tambahData.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_tambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahDataActionPerformed(evt);
            }
        });

        bt_hapusData.setBackground(new java.awt.Color(255, 0, 0));
        bt_hapusData.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_hapusData.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusData.setText("Hapus");
        bt_hapusData.setBorderPainted(false);
        bt_hapusData.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_hapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusDataActionPerformed(evt);
            }
        });

        bt_batalData.setBackground(new java.awt.Color(255, 102, 0));
        bt_batalData.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_batalData.setForeground(new java.awt.Color(255, 255, 255));
        bt_batalData.setText("Batal");
        bt_batalData.setBorderPainted(false);
        bt_batalData.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_batalData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalDataActionPerformed(evt);
            }
        });

        tblBarangMas.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tblBarangMas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarangMas.setGridColor(new java.awt.Color(204, 204, 204));
        tblBarangMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarangMas);

        t_cari.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_cari.setForeground(new java.awt.Color(153, 153, 153));
        t_cari.setText("Cari");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_cari.setPreferredSize(new java.awt.Dimension(30, 20));
        t_cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_cariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_cariFocusLost(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_cariKeyReleased(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/magnifying-glass.png"))); // NOI18N

        pn_detail.setBackground(new java.awt.Color(0, 11, 109));
        pn_detail.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Detail Barang Masuk");

        tblDetail.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetail.setGridColor(new java.awt.Color(204, 204, 204));
        tblDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetailMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDetail);

        bt_closeDet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/closeMenu.png"))); // NOI18N
        bt_closeDet.setContentAreaFilled(false);
        bt_closeDet.setOpaque(true);
        bt_closeDet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_closeDetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_closeDetMouseExited(evt);
            }
        });
        bt_closeDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_closeDetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_detailLayout = new javax.swing.GroupLayout(pn_detail);
        pn_detail.setLayout(pn_detailLayout);
        pn_detailLayout.setHorizontalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_closeDet)
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pn_detailLayout.setVerticalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(bt_closeDet))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
        );

        lb_idUser.setBackground(new java.awt.Color(255, 255, 255));
        lb_idUser.setForeground(new java.awt.Color(255, 255, 255));
        lb_idUser.setText("ID USER");

        bt_cetak.setBackground(new java.awt.Color(0, 102, 51));
        bt_cetak.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_cetak.setForeground(new java.awt.Color(255, 255, 255));
        bt_cetak.setText("Cetak");
        bt_cetak.setBorderPainted(false);
        bt_cetak.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataBarangLayout = new javax.swing.GroupLayout(dataBarang);
        dataBarang.setLayout(dataBarangLayout);
        dataBarangLayout.setHorizontalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addComponent(bt_tambahData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_hapusData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_batalData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addGap(579, 579, 579)
                        .addComponent(lb_idUser, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBarangLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(pn_detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dataBarangLayout.setVerticalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lb_idUser))
                .addGap(18, 18, 18)
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_tambahData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_hapusData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_batalData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(dataBarang, "card2");

        latihan_otomatis.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel7.setText("Tambah Data Barang Masuk");

        bt_simpan1.setBackground(new java.awt.Color(0, 11, 109));
        bt_simpan1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_simpan1.setForeground(new java.awt.Color(255, 255, 255));
        bt_simpan1.setText("Simpan");
        bt_simpan1.setBorderPainted(false);
        bt_simpan1.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpan1ActionPerformed(evt);
            }
        });

        bt_batal1.setBackground(new java.awt.Color(252, 102, 0));
        bt_batal1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_batal1.setForeground(new java.awt.Color(255, 255, 255));
        bt_batal1.setText("Batal");
        bt_batal1.setBorderPainted(false);
        bt_batal1.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batal1ActionPerformed(evt);
            }
        });

        pn_barMasuk.setBackground(new java.awt.Color(255, 255, 255));
        pn_barMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel19.setText("Tanggal Masuk");

        txt_tglMasuk.setBackground(new java.awt.Color(255, 255, 255));
        txt_tglMasuk.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_tglMasuk.setForeground(new java.awt.Color(255, 255, 255));
        txt_tglMasuk.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_tglMasuk.setPreferredSize(new java.awt.Dimension(1, 30));

        javax.swing.GroupLayout pn_barMasukLayout = new javax.swing.GroupLayout(pn_barMasuk);
        pn_barMasuk.setLayout(pn_barMasukLayout);
        pn_barMasukLayout.setHorizontalGroup(
            pn_barMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_barMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_barMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_barMasukLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_tglMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_barMasukLayout.setVerticalGroup(
            pn_barMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_barMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_tglMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pn_inputPes.setBackground(new java.awt.Color(255, 255, 255));
        pn_inputPes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel26.setText("No Pesan");

        txt_noPesan.setBackground(new java.awt.Color(255, 255, 255));
        txt_noPesan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_noPesan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_noPesan.setPreferredSize(new java.awt.Dimension(1, 30));

        jLabel27.setBackground(new java.awt.Color(0, 0, 0));
        jLabel27.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel27.setText("Tanggal Pesan");

        txt_tglPesan.setBackground(new java.awt.Color(255, 255, 255));
        txt_tglPesan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_tglPesan.setForeground(new java.awt.Color(0, 0, 0));
        txt_tglPesan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_tglPesan.setPreferredSize(new java.awt.Dimension(1, 30));

        pil_pesanan.setBackground(new java.awt.Color(0, 11, 109));
        pil_pesanan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        pil_pesanan.setForeground(new java.awt.Color(255, 255, 255));
        pil_pesanan.setText("Pilih");
        pil_pesanan.setPreferredSize(new java.awt.Dimension(75, 35));
        pil_pesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pil_pesananActionPerformed(evt);
            }
        });

        jLabel34.setBackground(new java.awt.Color(0, 0, 0));
        jLabel34.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel34.setText("Total Pesan");

        txt_totalPesan.setBackground(new java.awt.Color(255, 255, 255));
        txt_totalPesan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_totalPesan.setForeground(new java.awt.Color(0, 0, 0));
        txt_totalPesan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_totalPesan.setPreferredSize(new java.awt.Dimension(1, 30));

        jLabel35.setBackground(new java.awt.Color(0, 0, 0));
        jLabel35.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel35.setText("ID Pengguna");

        txt_idPeng.setBackground(new java.awt.Color(255, 255, 255));
        txt_idPeng.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_idPeng.setForeground(new java.awt.Color(0, 0, 0));
        txt_idPeng.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_idPeng.setPreferredSize(new java.awt.Dimension(1, 30));

        jLabel36.setBackground(new java.awt.Color(0, 0, 0));
        jLabel36.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel36.setText("ID Supplier");

        txt_idSup.setBackground(new java.awt.Color(255, 255, 255));
        txt_idSup.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_idSup.setForeground(new java.awt.Color(0, 0, 0));
        txt_idSup.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_idSup.setPreferredSize(new java.awt.Dimension(1, 30));

        bt_submit.setBackground(new java.awt.Color(0, 11, 109));
        bt_submit.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_submit.setForeground(new java.awt.Color(255, 255, 255));
        bt_submit.setText("SUBMIT");
        bt_submit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_submit.setPreferredSize(new java.awt.Dimension(175, 50));
        bt_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_submitActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 11, 109));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Masukkan No Pesan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_namaSup.setBackground(new java.awt.Color(255, 255, 255));
        txt_namaSup.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_namaSup.setForeground(new java.awt.Color(0, 0, 0));
        txt_namaSup.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_namaSup.setPreferredSize(new java.awt.Dimension(1, 30));

        jLabel37.setBackground(new java.awt.Color(0, 0, 0));
        jLabel37.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel37.setText("Nama Supplier");

        javax.swing.GroupLayout pn_inputPesLayout = new javax.swing.GroupLayout(pn_inputPes);
        pn_inputPes.setLayout(pn_inputPesLayout);
        pn_inputPesLayout.setHorizontalGroup(
            pn_inputPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_inputPesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_inputPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tglPesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pn_inputPesLayout.createSequentialGroup()
                        .addGroup(pn_inputPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addGroup(pn_inputPesLayout.createSequentialGroup()
                                .addComponent(txt_noPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pil_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_totalPesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_idPeng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_idSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_namaSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_inputPesLayout.setVerticalGroup(
            pn_inputPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_inputPesLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_inputPesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_noPesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pil_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_tglPesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_totalPesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_idPeng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_idSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_namaSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("TOTAL MASUK :");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Rp");

        txt_totalMas.setBackground(new java.awt.Color(255, 255, 255));
        txt_totalMas.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txt_totalMas.setForeground(new java.awt.Color(0, 0, 0));
        txt_totalMas.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_totalMas.setText(".......");
        txt_totalMas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txt_totalMas.setPreferredSize(new java.awt.Dimension(50, 30));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_totalMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txt_totalMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_detPem.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tbl_detPem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jPane_detPem.setViewportView(tbl_detPem);

        javax.swing.GroupLayout latihan_otomatisLayout = new javax.swing.GroupLayout(latihan_otomatis);
        latihan_otomatis.setLayout(latihan_otomatisLayout);
        latihan_otomatisLayout.setHorizontalGroup(
            latihan_otomatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(latihan_otomatisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(latihan_otomatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(latihan_otomatisLayout.createSequentialGroup()
                        .addGroup(latihan_otomatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(latihan_otomatisLayout.createSequentialGroup()
                                .addComponent(bt_simpan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addContainerGap(837, Short.MAX_VALUE))
                    .addGroup(latihan_otomatisLayout.createSequentialGroup()
                        .addGroup(latihan_otomatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pn_barMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_inputPes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)
                        .addGroup(latihan_otomatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(latihan_otomatisLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPane_detPem)))))
        );
        latihan_otomatisLayout.setVerticalGroup(
            latihan_otomatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, latihan_otomatisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(latihan_otomatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_simpan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(latihan_otomatisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(latihan_otomatisLayout.createSequentialGroup()
                        .addComponent(pn_barMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pn_inputPes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(latihan_otomatisLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPane_detPem, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE))))
        );

        mainPanel.add(latihan_otomatis, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_hapusDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusDataActionPerformed
//        hapusDataDetail();
        bt_tambahData.setText("Tambah");

    }//GEN-LAST:event_bt_hapusDataActionPerformed

    private void bt_batalDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalDataActionPerformed
        loadData();
        tampilPanel();
    }//GEN-LAST:event_bt_batalDataActionPerformed

    private void bt_tambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahDataActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(latihan_otomatis);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        setTanggal();
        txt_noPesan.setEnabled(false);
        txt_tglPesan.setEnabled(false);
        txt_totalPesan.setEnabled(false);
        txt_idPeng.setEnabled(false);
        txt_idSup.setEnabled(false);
        txt_namaSup.setEnabled(false);
        
        txt_totalMas.setText(String.valueOf(0));
        
//        loadDataSem();
        
    }//GEN-LAST:event_bt_tambahDataActionPerformed

    private void tblBarangMasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMasMouseClicked
          int row = tblBarangMas.getSelectedRow();
          String id = tblBarangMas.getValueAt(row, 0).toString();
          
//          bt_hapusData.setVisible(true);
//          bt_batalData.setVisible(true);
          pn_detail.setVisible(true);
          bt_closeDet.setBackground(null);
          List<model_detail_barangMasuk> list = serviceDet.getData(id);
          tblModelDet.setData(list);
    }//GEN-LAST:event_tblBarangMasMouseClicked

    private void t_cariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_cariFocusGained
        if(t_cari.getText().equalsIgnoreCase("Cari")) {
            t_cari.setText("");
            t_cari.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_t_cariFocusGained

    private void t_cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_cariFocusLost
        if(t_cari.getText().equalsIgnoreCase("")) {
            t_cari.setText("Cari");
        }
    }//GEN-LAST:event_t_cariFocusLost

    private void t_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyReleased
        pencarian();
    }//GEN-LAST:event_t_cariKeyReleased

    private void bt_closeDetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_closeDetMouseEntered
        bt_closeDet.setBackground(Color.red);
    }//GEN-LAST:event_bt_closeDetMouseEntered

    private void bt_closeDetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_closeDetMouseExited
        bt_closeDet.setBackground(null);
    }//GEN-LAST:event_bt_closeDetMouseExited

    private void bt_closeDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_closeDetActionPerformed
        pn_detail.setVisible(false);
    }//GEN-LAST:event_bt_closeDetActionPerformed

    private void bt_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cetakActionPerformed

    }//GEN-LAST:event_bt_cetakActionPerformed

    private void bt_simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpan1ActionPerformed
        String status = tbl_detPem.getModel().getValueAt(1, 6).toString();
        if(status.equals("Telah Sampai")) {
            JOptionPane.showMessageDialog(null, "Pesanan ini sudah di tambahkan");
        } else {
        simpanDataOtomatis();   
        }
    }//GEN-LAST:event_bt_simpan1ActionPerformed

    private void bt_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batal1ActionPerformed
        loadData();
        tampilPanel();
//        resetForm();
    }//GEN-LAST:event_bt_batal1ActionPerformed

    private void pil_pesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pil_pesananActionPerformed
        boolean closeable = true;
        dialog_pemesanan dgp = new dialog_pemesanan(null, closeable);
        dgp.setVisible(true);
        
        txt_noPesan.setText(dgp.pemesanan.getNo_pesan());
        txt_tglPesan.setText(dgp.pemesanan.getTgl_pesan());
        txt_totalPesan.setText(dgp.pemesanan.getTotal_pesan().toString());
        txt_idPeng.setText(lb_idUser.getText());
        txt_idSup.setText(dgp.pemesanan.getModel_supliyer_pem().getId_supliyer());
        txt_namaSup.setText(dgp.pemesanan.getModel_supliyer_pem().getNama_supliyer());
    }//GEN-LAST:event_pil_pesananActionPerformed

    private void bt_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_submitActionPerformed
        if(validasiInput()== true) {
        list = serviceDetPem.getData(txt_noPesan.getText());
        tblModelDetPem.setData(list);
        
        model_detail_pemesanan mdp = new model_detail_pemesanan();
        model_pemesanan mp = new model_pemesanan();
        
        String no_pesan = txt_noPesan.getText();
        Long subtotal = mdp.getSubtotal_pesan();
        
        mp.setNo_pesan(no_pesan);
        mdp.setMod_pemesanan_detPem(mp);
        mdp.setSubtotal_pesan(subtotal);
        serviceDetPem.sumTotalDetail(mdp);
        txt_totalMas.setText(mdp.getSubtotal_pesan().toString());  
        }
        
        
    }//GEN-LAST:event_bt_submitActionPerformed

    private void tblDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDetailMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_batal1;
    private javax.swing.JButton bt_batalData;
    private javax.swing.JButton bt_cetak;
    private javax.swing.JButton bt_closeDet;
    private javax.swing.JButton bt_hapusData;
    private javax.swing.JButton bt_simpan1;
    private javax.swing.JButton bt_submit;
    private javax.swing.JButton bt_tambahData;
    private javax.swing.JPanel dataBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jPane_detPem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel latihan_otomatis;
    private javax.swing.JLabel lb_idUser;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton pil_pesanan;
    private javax.swing.JPanel pn_barMasuk;
    private javax.swing.JPanel pn_detail;
    private javax.swing.JPanel pn_inputPes;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTable tblBarangMas;
    private javax.swing.JTable tblDetail;
    private javax.swing.JTable tbl_detPem;
    private javax.swing.JTextField txt_idPeng;
    private javax.swing.JTextField txt_idSup;
    private javax.swing.JTextField txt_namaSup;
    private javax.swing.JTextField txt_noPesan;
    private javax.swing.JTextField txt_tglMasuk;
    private javax.swing.JTextField txt_tglPesan;
    private javax.swing.JTextField txt_totalMas;
    private javax.swing.JTextField txt_totalPesan;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        bt_hapusData.setVisible(false);
        bt_batalData.setVisible(false);
        List<model_barangMasuk> list = serviceMas.getData();
        tblModelMas.setData(list);
    }
    
//    private void loadDataSem() {
//        List<sementara_masuk> list = serviceSem.getData();
//        tblModelSem.setData(list);
//    }
    
//    private void bersihBarang() {
//        t_kodeBarang.setText("");
//        t_namaBarang.setText("");
//        cbx_satuan.setSelectedItem("Pilih Satuan");
//        t_harga.setText("");
//        t_jumlah.setText("");
//        t_subTotal.setText("");
//    }
    
    private void setTanggal() {
        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        txt_tglMasuk.setText(sdf.format(now));
        txt_tglMasuk.setEnabled(false);
    }
    
//    private void hapusDataSementara() {
//        int index = tbl_semMas.getSelectedRow();
//        if(index != -1) {
//            sementara_masuk semMas = tblModelSem.getData(tbl_semMas.convertRowIndexToModel(index));
//            if(JOptionPane.showConfirmDialog(null, "Yakin data ingin dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
//                model_detail_barangMasuk mdb = new model_detail_barangMasuk();
//                Long subTotal = Long.parseLong(t_subTotal.getText());
//                mdb.setSubtotal_masuk(subTotal);
//
//                serviceSem.hapusData(semMas);
//                serviceDet.sumTotal(mdb);
//                tblModelSem.hapusData(index);
//                t_totalMas.setText(mdb.getSubtotal_masuk().toString());
//                
//                bt_tambahkan.setText("Tambahkan");
//                bt_tambahkan.setBackground(new Color(0,11,109));
//                bt_batalkan.setVisible(false);
//                bt_hapuskan.setVisible(false);
//                loadDataSem();
//                bersihBarang();
////                resetForm();
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Pilih dahulu data dahulu yang akan dihapus");
//        }
//    }
    
//    private void resetForm() {
//        bt_simpan.requestFocus();
//        bt_simpan.setText("Tambah");
//        t_noMasuk.setText("");
//        t_namaBarang.setText("");
//        t_harga.setText("");
//        
//    }
    
    private void tampilPanel() {
        mainPanel.removeAll();
        String id = lb_idUser.getText();
        mainPanel.add(new transaksi_barangMasuk(id));
        lb_idUser.setText(id);
        mainPanel.repaint();
        mainPanel.revalidate();
    }
    
//    private void aktif() {
//        t_namaBarang.setEnabled(true);
//        t_harga.setEnabled(true);
//        
//    }
    
//    private void simpanData() {
////        if(validasiInput() == true) {
//            String no_masuk = t_noMasuk.getText();
////            String kode_barang = t_kodeBarang.getText();
//            String tgl_masuk = t_tanggal.getText();
////            Long subTotal = Long.parseLong(t_subTotal.getText());
//            String id_supliyer = t_idSup.getText();
//            String id_pengguna = lb_idUser.getText();
////            String status = "Sedang di kirim";
//            Long total_pesan = Long.parseLong(t_totalMas.getText());
//            
//            model_pengguna modPeng = new model_pengguna();
//            model_supliyer modSup = new model_supliyer();
//            model_barang modBar = new model_barang();
//            model_barangMasuk modBarMas = new model_barangMasuk();
//            model_detail_barangMasuk modDetBar = new model_detail_barangMasuk();
//
////          Simpan table pemesanan
////            modBar.setKode_barang(kode_barang);
//            modBarMas.setNo_masuk(no_masuk);
//            modBarMas.setTgl_masuk(tgl_masuk);
//            modBarMas.setTotal_masuk(total_pesan);
//            modSup.setId_supliyer(id_supliyer);
//            modPeng.setId_pengguna(id_pengguna);
//            modBarMas.setMod_pengguna(modPeng);
//            modBarMas.setMod_supliyer(modSup);
//            
////          Simpan table detail pemesanan
//            modDetBar.setMod_barangMas_detMas(modBarMas);
//            modDetBar.setMod_barang_detMas(modBar);
////            modDetPem.setStatus(status);
//            
//            
//            serviceMas.tambahData(modBarMas);
//            serviceDet.tambahData(modDetBar);
//            serviceDet.hapusSementara(modDetBar);
//            tblModelMas.tambahData(modBarMas);
//            loadData();
////            resetForm();
//            tampilPanel();
//            bt_simpan.setText("Tambah");
////        }
//    }
    
//    private void hapusData() {
//        int index = tblBarangMas.getSelectedRow();
//        if(index != -1) {
//            model_barangMasuk modBarMas = tblModelMas.getData(tblBarangMas.convertRowIndexToModel(index));
//            serviceMas.hapusData(modBarMas);
//            tblModelMas.hapusData(index);
//            loadData();
//            tblDetail.setVisible(false);
//
//        }
//    }
    
//    private void hapusDataDetail() {
//        int index = tblDetail.getSelectedRow();
//        if(index != -1) {
//            model_detail_barangMasuk modDetBar = tblModelDet.getData(tblDetail.convertRowIndexToModel(index));
//            if(JOptionPane.showConfirmDialog(null, "Yakin data ingin dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
//                serviceDet.hapusData(modDetBar);
//                tblModelDet.hapusData(index);
//                loadData();
//                tblDetail.setVisible(false);
////                resetForm();
//            } else {
//                JOptionPane.showMessageDialog(null, "Pilih dahulu data yang akan dihapus");
//            }
//            
//        }
//        
//    }
    
    
//    private void tambahDataSementara() {
//        String kode_barang = t_kodeBarang.getText();
//        String nama_barang = t_namaBarang.getText();
//        
//        sementara_masuk semMas = new sementara_masuk();
//        model_barang modBar = new model_barang();
//        
//        modBar.setKode_barang(kode_barang);
//        modBar.setNama_barang(nama_barang);   
//        semMas.setMdl_brg(modBar);
//        
//        if(serviceSem.validasiNamaBarang(semMas)==true) {  
//        
//            if(validasiInput()==true) {   
//        String kode = t_kodeBarang.getText();
//        String nama = t_namaBarang.getText();
//        String satuan = cbx_satuan.getSelectedItem().toString();
//        Long harga = Long.parseLong(t_harga.getText());
//        Integer jumlah = Integer.parseInt(t_jumlah.getText());
//        Long subTotal = Long.parseLong(t_subTotal.getText());
////        String status = "Sedang Dikirim";
//        
//        model_barang mb = new model_barang();
//        model_detail_barangMasuk mdbm = new model_detail_barangMasuk();
//        sementara_masuk sm = new sementara_masuk();
//        
//        mb.setKode_barang(kode);
//        mb.setNama_barang(nama);
//        mb.setSatuan(satuan);
//        mb.setHarga(harga);
//        
//        mdbm.setJml_masuk(jumlah);
//        mdbm.setSubtotal_masuk(subTotal);
//        Long subtotal = mdbm.getSubtotal_masuk();
//        mdbm.setSubtotal_masuk(subtotal);
////        mdp.setStatus(status);
//        
//        sm.setMdl_brg(mb);
//        sm.setMdl_mdbm(mdbm);
//        
//        serviceSem.tambahData(sm);
//        serviceDet.sumTotal(mdbm);
//        t_totalMas.setText(mdbm.getSubtotal_masuk().toString());
//        if(JOptionPane.showConfirmDialog(this, "Mau Tambah barang?", "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
//        bersihBarang();
//        
//        } else {
//        bersihBarang();
//        }
//        
//        loadDataSem();
//        }
//      }
//    }
//    
//    private void perbaruiDataSementara() {
//        int index = tbl_semMas.getSelectedRow();
//        if(index != -1) {
//            sementara_masuk semenMas = tblModelSem.getData(tbl_semMas.convertRowIndexToModel(index));
//            
//            if(validasiInput() == true) {
//            String kode_barang = t_kodeBarang.getText();
//            String nama_barang = t_namaBarang.getText();
//            String satuan = cbx_satuan.getSelectedItem().toString();
//            Long harga = Long.parseLong(t_harga.getText());
//            Integer jumlah = Integer.parseInt(t_jumlah.getText());
//            Long subTotal = Long.parseLong(t_subTotal.getText());
////            String status = "Sedang dikirim";
//            
//            model_barang mb = new model_barang();
//            model_detail_barangMasuk mdbm = new model_detail_barangMasuk();
//            sementara_masuk sm = new sementara_masuk();
//            
//            mb.setKode_barang(kode_barang);
//            mb.setNama_barang(nama_barang);
//            mb.setSatuan(satuan);
//            mb.setHarga(harga);
//            mdbm.setJml_masuk(jumlah);
//            mdbm.setSubtotal_masuk(subTotal);
////            mdp.setStatus(status);
//            
//            sm.setMdl_brg(mb);
//            sm.setMdl_mdbm(mdbm);
//            
//            serviceSem.perbaruiData(sm);
//            serviceDet.sumTotal(mdbm);
//            tblModelSem.perbaruiData(index, sm);
//            t_totalMas.setText(mdbm.getSubtotal_masuk().toString());
//            
//            bt_tambahkan.setText("Tambahkan");
//            bt_tambahkan.setBackground(new Color(0,11,109));
//            bt_batalkan.setVisible(false);
//            bt_hapuskan.setVisible(false);
//            
//            loadDataSem();
//            bersihBarang();
//        }
//    }
//}

//    fungsi latihan submit start
    
    private void simpanDataOtomatis() {
        if(validasiInput() == true) {  
        String no_masuk = txt_noPesan.getText();
        String tgl_masuk = txt_tglMasuk.getText();
        Long total_masuk = Long.parseLong(txt_totalMas.getText());
        String id_pengguna = txt_idPeng.getText();
        String id_supliyer = txt_idSup.getText();
        
        model_pengguna modPeng = new model_pengguna();
        model_supliyer modSup = new model_supliyer();
        model_barangMasuk mbm = new model_barangMasuk();
        
//      simpan table barang masuk
        mbm.setNo_masuk(no_masuk);
        mbm.setTgl_masuk(tgl_masuk);
        mbm.setTotal_masuk(total_masuk);
        modPeng.setId_pengguna(id_pengguna);
        modSup.setId_supliyer(id_supliyer);
        mbm.setMod_pengguna(modPeng);
        mbm.setMod_supliyer(modSup);
        
//      simpan table detail pemesanan  
        serviceMas.tambahData(mbm);
        serviceDet.tambahData(list);
        tblModelMas.tambahData(mbm);
        loadData();
        tampilPanel();
        }
    }
    
    private void pencarian() {
        int row = tblBarangMas.getSelectedRow();
        String no_masuk = tblBarangMas.getValueAt(row, 0).toString();
        List<model_detail_barangMasuk> list = serviceDet.pencarian(t_cari.getText(), no_masuk);
        tblModelDet.setData(list);
    }
    
    private boolean validasiInput() {
        boolean valid = false;
        if(txt_noPesan.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No Pesan tidak boleh kosong");
        } else {
            valid = true;
        }
        return valid;
    }
    
    static public class HeaderColor extends DefaultTableCellRenderer{

        public HeaderColor() {
            setOpaque(true);
        }
        
        public Component getTableCellRendererComponent(JTable tbl_contoh, Object value, boolean selected, boolean focused, int row, int column) {
            super.getTableCellRendererComponent(tbl_contoh, value, selected, focused, row, column);
            setBackground(new Color(0,139,185,255));
            setForeground(new Color(255, 255, 255));
            setFont(new Font(null, Font.BOLD, 18));
            return this;
        }
    
    }
    
}
