package view_transaksi;
import config.koneksi;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import java.awt.Color;
import control.Control_pemesanan;
import control.Control_detPemesanan;
import crud.trans_pemesanan;
import crud.trans_detPemesanan;
import crud.trans_semPesan;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.model_pemesanan;
import model.model_detail_pemesanan;
import model.sementara_pesan;
import model.model_barang;
import model.model_pengguna;
import model.model_supliyer;
import tableModel.tm_pemesanan;
import tableModel.tm_detPemesanan;
import tableModel.tm_semPesan;
import view_transaksi.dialog_supliyer;
import control.Control_semPesan;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;


public class transaksi_pemesanan extends javax.swing.JPanel {
    private Control_pemesanan servicePem = new trans_pemesanan();
    private Control_detPemesanan serviceDet = new trans_detPemesanan();
    private Control_semPesan serviceSem = new trans_semPesan();
    
    private tm_pemesanan tblModelPem = new tm_pemesanan();
    private tm_detPemesanan tblModelDet = new tm_detPemesanan();
    private tm_semPesan tblModelSem = new tm_semPesan();
    
    public transaksi_pemesanan(String id) {
        initComponents();
        tblPemesanan.getTableHeader().setDefaultRenderer(new HeaderColor());
        tblDetail.getTableHeader().setDefaultRenderer(new HeaderColor());
        tbl_semPes.getTableHeader().setDefaultRenderer(new HeaderColor());
        tblPemesanan.setRowHeight(50);
        tblDetail.setRowHeight(50);
        tbl_semPes.setRowHeight(50);
        lb_idUser.setText(id);
        tblPemesanan.setModel(tblModelPem);
        tblDetail.setModel(tblModelDet);
        tbl_semPes.setModel(tblModelSem);
        t_hargaJual.setVisible(false);
        pn_detail.setVisible(false);
        bt_cetak.setVisible(false);
        
        loadData();
        loadDataSem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel3 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        dataBarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_tambahData = new javax.swing.JButton();
        bt_hapusData = new javax.swing.JButton();
        bt_batalData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPemesanan = new javax.swing.JTable();
        t_cari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pn_detail = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDetail = new javax.swing.JTable();
        bt_closeDet = new javax.swing.JButton();
        lb_idUser = new javax.swing.JLabel();
        bt_cetak = new javax.swing.JButton();
        tambahBarang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bt_simpan = new javax.swing.JButton();
        bt_batal = new javax.swing.JButton();
        pn_pesan = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        t_noPesan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        t_tanggal = new javax.swing.JTextField();
        pn_supplier = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        t_idSup = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        t_namaSup = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pilihSup = new javax.swing.JButton();
        pn_barang = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        t_kodeBarang = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        t_namaBarang = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bt_pilihBar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        t_harga = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        t_jumlah = new javax.swing.JTextField();
        t_subTotal = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cbx_satuan = new javax.swing.JComboBox<>();
        bt_tambahkan = new javax.swing.JButton();
        bt_batalkan = new javax.swing.JButton();
        bt_hapuskan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_semPes = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t_totalPem = new javax.swing.JTextField();
        t_hargaJual = new javax.swing.JTextField();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataBarang.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Transaksi Pemesanan");

        bt_tambahData.setBackground(new java.awt.Color(0, 11, 109));
        bt_tambahData.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_tambahData.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahData.setText("Tambah");
        bt_tambahData.setBorderPainted(false);
        bt_tambahData.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_tambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahDataActionPerformed(evt);
            }
        });

        bt_hapusData.setBackground(new java.awt.Color(255, 0, 0));
        bt_hapusData.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_hapusData.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusData.setText("Hapus");
        bt_hapusData.setBorderPainted(false);
        bt_hapusData.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_hapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusDataActionPerformed(evt);
            }
        });

        bt_batalData.setBackground(new java.awt.Color(255, 102, 0));
        bt_batalData.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_batalData.setForeground(new java.awt.Color(255, 255, 255));
        bt_batalData.setText("Batal");
        bt_batalData.setBorderPainted(false);
        bt_batalData.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_batalData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalDataActionPerformed(evt);
            }
        });

        tblPemesanan.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tblPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPemesanan.setGridColor(new java.awt.Color(204, 204, 204));
        tblPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPemesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPemesanan);

        t_cari.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        t_cari.setForeground(new java.awt.Color(153, 153, 153));
        t_cari.setText("Cari");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_cari.setPreferredSize(new java.awt.Dimension(30, 20));
        t_cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_cariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_cariFocusLost(evt);
            }
        });
        t_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cariActionPerformed(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_cariKeyReleased(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/magnifying-glass.png"))); // NOI18N

        pn_detail.setBackground(new java.awt.Color(0, 11, 109));
        pn_detail.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Detail Transaksi");

        tblDetail.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetail.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(tblDetail);

        bt_closeDet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/closeMenu.png"))); // NOI18N
        bt_closeDet.setContentAreaFilled(false);
        bt_closeDet.setOpaque(true);
        bt_closeDet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_closeDetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_closeDetMouseExited(evt);
            }
        });
        bt_closeDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_closeDetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_detailLayout = new javax.swing.GroupLayout(pn_detail);
        pn_detail.setLayout(pn_detailLayout);
        pn_detailLayout.setHorizontalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_closeDet)
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1146, Short.MAX_VALUE)
        );
        pn_detailLayout.setVerticalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(bt_closeDet))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
        );

        lb_idUser.setBackground(new java.awt.Color(255, 255, 255));
        lb_idUser.setForeground(new java.awt.Color(255, 255, 255));
        lb_idUser.setText("ID USER");

        bt_cetak.setBackground(new java.awt.Color(0, 102, 51));
        bt_cetak.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_cetak.setForeground(new java.awt.Color(255, 255, 255));
        bt_cetak.setText("Cetak");
        bt_cetak.setBorderPainted(false);
        bt_cetak.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataBarangLayout = new javax.swing.GroupLayout(dataBarang);
        dataBarang.setLayout(dataBarangLayout);
        dataBarangLayout.setHorizontalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addComponent(bt_tambahData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_hapusData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_batalData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11))
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(681, 681, 681)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_idUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_cari, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1146, Short.MAX_VALUE)
            .addComponent(pn_detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dataBarangLayout.setVerticalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lb_idUser))
                .addGap(18, 18, 18)
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_tambahData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_hapusData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_batalData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(dataBarang, "card2");

        tambahBarang.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel3.setText("Tambah Pemesanan");

        bt_simpan.setBackground(new java.awt.Color(0, 11, 109));
        bt_simpan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_simpan.setForeground(new java.awt.Color(255, 255, 255));
        bt_simpan.setText("Simpan");
        bt_simpan.setBorderPainted(false);
        bt_simpan.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpanActionPerformed(evt);
            }
        });

        bt_batal.setBackground(new java.awt.Color(252, 102, 0));
        bt_batal.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_batal.setForeground(new java.awt.Color(255, 255, 255));
        bt_batal.setText("Batal");
        bt_batal.setBorderPainted(false);
        bt_batal.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });

        pn_pesan.setBackground(new java.awt.Color(255, 255, 255));
        pn_pesan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setText("No Pesan");

        t_noPesan.setBackground(new java.awt.Color(255, 255, 255));
        t_noPesan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_noPesan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_noPesan.setPreferredSize(new java.awt.Dimension(1, 30));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel15.setText("Tahun/Bulan/Tanggal");

        t_tanggal.setBackground(new java.awt.Color(255, 255, 255));
        t_tanggal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        t_tanggal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_tanggal.setPreferredSize(new java.awt.Dimension(1, 30));

        javax.swing.GroupLayout pn_pesanLayout = new javax.swing.GroupLayout(pn_pesan);
        pn_pesan.setLayout(pn_pesanLayout);
        pn_pesanLayout.setHorizontalGroup(
            pn_pesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pesanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_pesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_pesanLayout.createSequentialGroup()
                        .addGroup(pn_pesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(t_tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_noPesan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_pesanLayout.setVerticalGroup(
            pn_pesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pesanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_noPesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(t_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pn_supplier.setBackground(new java.awt.Color(255, 255, 255));
        pn_supplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel16.setText("ID Supplier");

        t_idSup.setBackground(new java.awt.Color(255, 255, 255));
        t_idSup.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_idSup.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_idSup.setPreferredSize(new java.awt.Dimension(1, 30));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel17.setText("Nama Supplier");

        t_namaSup.setBackground(new java.awt.Color(255, 255, 255));
        t_namaSup.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_namaSup.setForeground(new java.awt.Color(0, 0, 0));
        t_namaSup.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_namaSup.setPreferredSize(new java.awt.Dimension(1, 30));

        jPanel1.setBackground(new java.awt.Color(0, 11, 109));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Supplier");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel2)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pilihSup.setBackground(new java.awt.Color(0, 11, 109));
        pilihSup.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        pilihSup.setForeground(new java.awt.Color(255, 255, 255));
        pilihSup.setText("Pilih");
        pilihSup.setPreferredSize(new java.awt.Dimension(75, 35));
        pilihSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihSupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_supplierLayout = new javax.swing.GroupLayout(pn_supplier);
        pn_supplier.setLayout(pn_supplierLayout);
        pn_supplierLayout.setHorizontalGroup(
            pn_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_supplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_namaSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pn_supplierLayout.createSequentialGroup()
                        .addGroup(pn_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(0, 252, Short.MAX_VALUE))
                    .addGroup(pn_supplierLayout.createSequentialGroup()
                        .addComponent(t_idSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilihSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_supplierLayout.setVerticalGroup(
            pn_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_supplierLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_idSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pilihSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pn_barang.setBackground(new java.awt.Color(255, 255, 255));
        pn_barang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel20.setText("Kode Barang");

        t_kodeBarang.setBackground(new java.awt.Color(255, 255, 255));
        t_kodeBarang.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_kodeBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_kodeBarang.setPreferredSize(new java.awt.Dimension(1, 30));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel21.setText("Nama Barang");

        t_namaBarang.setBackground(new java.awt.Color(255, 255, 255));
        t_namaBarang.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_namaBarang.setForeground(new java.awt.Color(0, 0, 0));
        t_namaBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_namaBarang.setPreferredSize(new java.awt.Dimension(1, 30));

        jPanel2.setBackground(new java.awt.Color(0, 11, 109));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Barang");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        bt_pilihBar.setBackground(new java.awt.Color(0, 11, 109));
        bt_pilihBar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_pilihBar.setForeground(new java.awt.Color(255, 255, 255));
        bt_pilihBar.setText("Pilih");
        bt_pilihBar.setPreferredSize(new java.awt.Dimension(75, 35));
        bt_pilihBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pilihBarActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel22.setText("Satuan");

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel23.setText("Harga Beli");

        t_harga.setBackground(new java.awt.Color(255, 255, 255));
        t_harga.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_harga.setForeground(new java.awt.Color(0, 0, 0));
        t_harga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_harga.setPreferredSize(new java.awt.Dimension(1, 30));
        t_harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_hargaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_hargaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_hargaKeyTyped(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel24.setText("Jumlah");

        t_jumlah.setBackground(new java.awt.Color(255, 255, 255));
        t_jumlah.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_jumlah.setForeground(new java.awt.Color(0, 0, 0));
        t_jumlah.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_jumlah.setPreferredSize(new java.awt.Dimension(1, 30));
        t_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_jumlahKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_jumlahKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_jumlahKeyTyped(evt);
            }
        });

        t_subTotal.setBackground(new java.awt.Color(255, 255, 255));
        t_subTotal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_subTotal.setForeground(new java.awt.Color(0, 0, 0));
        t_subTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_subTotal.setPreferredSize(new java.awt.Dimension(1, 30));

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel25.setText("Subtotal");

        cbx_satuan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        cbx_satuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Satuan", "Pcs", "Pack" }));
        cbx_satuan.setPreferredSize(new java.awt.Dimension(110, 30));

        bt_tambahkan.setBackground(new java.awt.Color(0, 11, 109));
        bt_tambahkan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_tambahkan.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahkan.setText("Tambahkan");
        bt_tambahkan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_tambahkan.setPreferredSize(new java.awt.Dimension(175, 50));
        bt_tambahkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahkanActionPerformed(evt);
            }
        });

        bt_batalkan.setBackground(new java.awt.Color(252, 102, 0));
        bt_batalkan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_batalkan.setForeground(new java.awt.Color(255, 255, 255));
        bt_batalkan.setText("Batal");
        bt_batalkan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_batalkan.setPreferredSize(new java.awt.Dimension(175, 50));
        bt_batalkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalkanActionPerformed(evt);
            }
        });

        bt_hapuskan.setBackground(new java.awt.Color(255, 0, 0));
        bt_hapuskan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_hapuskan.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapuskan.setText("Hapus");
        bt_hapuskan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_hapuskan.setPreferredSize(new java.awt.Dimension(175, 50));
        bt_hapuskan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapuskanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_barangLayout = new javax.swing.GroupLayout(pn_barang);
        pn_barang.setLayout(pn_barangLayout);
        pn_barangLayout.setHorizontalGroup(
            pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_barangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_barangLayout.createSequentialGroup()
                        .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_namaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pn_barangLayout.createSequentialGroup()
                                .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addGap(0, 265, Short.MAX_VALUE))
                            .addGroup(pn_barangLayout.createSequentialGroup()
                                .addComponent(t_kodeBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_pilihBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_barangLayout.createSequentialGroup()
                        .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_hapuskan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_batalkan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_harga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_jumlah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_subTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_barangLayout.createSequentialGroup()
                                .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addGap(0, 283, Short.MAX_VALUE))
                            .addComponent(cbx_satuan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_tambahkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        pn_barangLayout.setVerticalGroup(
            pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_barangLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_kodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_pilihBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_tambahkan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_batalkan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_hapuskan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_semPes.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tbl_semPes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_semPes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_semPesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_semPes);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("TOTAL PEMESANAN :");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Rp");

        t_totalPem.setBackground(new java.awt.Color(255, 255, 255));
        t_totalPem.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        t_totalPem.setForeground(new java.awt.Color(0, 0, 0));
        t_totalPem.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t_totalPem.setText(".......");
        t_totalPem.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_totalPem.setPreferredSize(new java.awt.Dimension(50, 30));

        t_hargaJual.setText("jTextField1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_totalPem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_hargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(t_totalPem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(t_hargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout tambahBarangLayout = new javax.swing.GroupLayout(tambahBarang);
        tambahBarang.setLayout(tambahBarangLayout);
        tambahBarangLayout.setHorizontalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahBarangLayout.createSequentialGroup()
                        .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pn_supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_pesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(tambahBarangLayout.createSequentialGroup()
                        .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahBarangLayout.createSequentialGroup()
                                .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addContainerGap(894, Short.MAX_VALUE))))
        );
        tambahBarangLayout.setVerticalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahBarangLayout.createSequentialGroup()
                        .addComponent(pn_pesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(tambahBarangLayout.createSequentialGroup()
                        .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahBarangLayout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(tambahBarangLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jScrollPane2)))
                        .addContainerGap())))
        );

        mainPanel.add(tambahBarang, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_hapusDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusDataActionPerformed
        hapusDataDetail();
        bt_tambahData.setText("Tambah");

    }//GEN-LAST:event_bt_hapusDataActionPerformed

    private void bt_batalDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalDataActionPerformed
        loadData();
        tampilPanel();
    }//GEN-LAST:event_bt_batalDataActionPerformed

    private void bt_tambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahDataActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(tambahBarang);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        t_noPesan.setText(servicePem.nomor());
        t_noPesan.setEnabled(false);
        setTanggal();
        t_idSup.setEnabled(false);
        t_namaSup.setEnabled(false);
        t_kodeBarang.setEnabled(false);
        t_namaBarang.setEnabled(false);
        t_subTotal.setEnabled(false);
        bt_batalkan.setVisible(false);
        bt_hapuskan.setVisible(false);
        
        model_detail_pemesanan mdp = new model_detail_pemesanan();
        Long subtotal = mdp.getSubtotal_pesan();
        mdp.setSubtotal_pesan(subtotal);
        serviceDet.sumTotal(mdp);
        t_totalPem.setText(String.valueOf(mdp.getSubtotal_pesan()));   
        
        loadDataSem();
//        if(bt_tambahData.getText().equalsIgnoreCase("Ubah")) {
//            dataTable();
//        }
        
    }//GEN-LAST:event_bt_tambahDataActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        loadData();
        tampilPanel();
        resetForm();
    }//GEN-LAST:event_bt_batalActionPerformed

    private void tblPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPemesananMouseClicked
          int row = tblPemesanan.getSelectedRow();
          String id = tblPemesanan.getValueAt(row, 0).toString();
          pn_detail.setVisible(true);
          bt_closeDet.setBackground(null);
          List<model_detail_pemesanan> list = serviceDet.getData(id);
          tblModelDet.setData(list);
    }//GEN-LAST:event_tblPemesananMouseClicked

    private void bt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpanActionPerformed
       if(bt_simpan.getText().equalsIgnoreCase("Simpan")) {
           if(JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menambah pemesanan?\nBarang yang sudah dipesan tidak dapat di perbarui", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION)== JOptionPane.OK_OPTION) {
           simpanData();   
           } 
       } else if(bt_simpan.getText().equals("Perbarui")) {
//           perbaruiData();
       }
           
    }//GEN-LAST:event_bt_simpanActionPerformed

    private void t_cariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_cariFocusGained
        if(t_cari.getText().equalsIgnoreCase("Cari")) {
            t_cari.setText("");
            t_cari.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_t_cariFocusGained

    private void t_cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_cariFocusLost
        if(t_cari.getText().equalsIgnoreCase("")) {
            t_cari.setText("Cari");
        }
    }//GEN-LAST:event_t_cariFocusLost

    private void t_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyReleased
        pencarian();
    }//GEN-LAST:event_t_cariKeyReleased

    private void bt_closeDetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_closeDetMouseEntered
        bt_closeDet.setBackground(Color.red);
    }//GEN-LAST:event_bt_closeDetMouseEntered

    private void bt_closeDetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_closeDetMouseExited
        bt_closeDet.setBackground(null);
    }//GEN-LAST:event_bt_closeDetMouseExited

    private void bt_closeDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_closeDetActionPerformed
        pn_detail.setVisible(false);
    }//GEN-LAST:event_bt_closeDetActionPerformed

    private void pilihSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihSupActionPerformed
        boolean closeable = true;
        dialog_supliyer ds = new dialog_supliyer(null, closeable);
        ds.setVisible(true);
        
        t_idSup.setText(ds.supliyer.getId_supliyer());
        t_namaSup.setText(ds.supliyer.getNama_supliyer());
        
    }//GEN-LAST:event_pilihSupActionPerformed

    private void bt_pilihBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pilihBarActionPerformed
        boolean closeable = true;
        dialog_barang db = new dialog_barang(null, closeable);
        db.setVisible(true);

        String kode = db.Barang.getKode_barang();
        String nama = db.Barang.getNama_barang();
        String satuan = db.Barang.getSatuan();
        String harga = db.Barang.getHarga().toString();

        t_kodeBarang.setText(kode);
        t_namaBarang.setText(nama);
        cbx_satuan.setSelectedItem(satuan);
        t_hargaJual.setText(harga);
        t_harga.requestFocus();    
    }//GEN-LAST:event_bt_pilihBarActionPerformed

    private void t_hargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_hargaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_jumlah.requestFocus();
        }
    }//GEN-LAST:event_t_hargaKeyPressed

    private void bt_tambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahkanActionPerformed
        if(bt_tambahkan.getText().equals("Tambahkan")) {
            tambahDataSementara();
        } else if(bt_tambahkan.getText().equals("Perbarui")) {
            perbaruiDataSementara();
        }
    }//GEN-LAST:event_bt_tambahkanActionPerformed

    private void tbl_semPesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_semPesMouseClicked
        int row = tbl_semPes.getSelectedRow();
        
        t_kodeBarang.setText(tbl_semPes.getModel().getValueAt(row, 0).toString());
        t_namaBarang.setText(tbl_semPes.getModel().getValueAt(row, 1).toString());
        cbx_satuan.setSelectedItem(tbl_semPes.getModel().getValueAt(row, 2).toString());
        t_harga.setText(tbl_semPes.getModel().getValueAt(row, 3).toString());
        t_jumlah.setText(tbl_semPes.getModel().getValueAt(row, 4).toString());
        t_subTotal.setText(tbl_semPes.getModel().getValueAt(row, 5).toString());
        
        bt_tambahkan.setText("Perbarui");
        bt_tambahkan.setBackground(new Color(51, 102, 0));
        bt_batalkan.setVisible(true);
        bt_hapuskan.setVisible(true);
        
    }//GEN-LAST:event_tbl_semPesMouseClicked

    private void bt_batalkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalkanActionPerformed
        loadDataSem();
        bersihBarang();
        bt_tambahkan.setText("Tambahkan");
        bt_tambahkan.setBackground(new Color(0, 11, 109));
        bt_batalkan.setVisible(false);
        bt_hapuskan.setVisible(false);
    }//GEN-LAST:event_bt_batalkanActionPerformed

    private void bt_hapuskanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapuskanActionPerformed
        hapusDataSementara();
    }//GEN-LAST:event_bt_hapuskanActionPerformed

    private void t_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_jumlahKeyReleased
            long harga = Long.parseLong(t_harga.getText());
            int jumlah;
            String inputJumlah = t_jumlah.getText();
            
            if(inputJumlah.isEmpty()) {
                jumlah = 0;
            } else {
                jumlah = Integer.parseInt(inputJumlah);
            }
            
            long subTotal = jumlah * harga;
            t_subTotal.setText(Long.toString(subTotal));
            

    }//GEN-LAST:event_t_jumlahKeyReleased

    private void t_jumlahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_jumlahKeyPressed
//       if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
//           bt_tambahkanActionPerformed(new ActionEvent(evt.getSource(), evt.getID(), null));
//       }
    }//GEN-LAST:event_t_jumlahKeyPressed

    private void bt_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cetakActionPerformed

    }//GEN-LAST:event_bt_cetakActionPerformed

    private void t_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_cariActionPerformed

    private void t_hargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_hargaKeyTyped
        char enter = evt.getKeyChar();
        if(Character.isDigit(enter) == false) {
        evt.consume(); 
        }
    }//GEN-LAST:event_t_hargaKeyTyped

    private void t_jumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_jumlahKeyTyped
        char enter = evt.getKeyChar();
        if(Character.isDigit(enter) == false) {
        evt.consume(); 
        }
    }//GEN-LAST:event_t_jumlahKeyTyped

    private void t_hargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_hargaKeyReleased
        long harga;
        int jumlah = Integer.parseInt(t_jumlah.getText());
        String inputHarga = String.valueOf(t_harga.getText());
        
        if(inputHarga.isEmpty()) {
            harga = 0;
        } else {
            harga = Long.parseLong(inputHarga);
        }
        long hasil = harga * jumlah;
        String sub_total = String.valueOf(hasil);
        t_subTotal.setText(sub_total);
    }//GEN-LAST:event_t_hargaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_batalData;
    private javax.swing.JButton bt_batalkan;
    private javax.swing.JButton bt_cetak;
    private javax.swing.JButton bt_closeDet;
    private javax.swing.JButton bt_hapusData;
    private javax.swing.JButton bt_hapuskan;
    private javax.swing.JButton bt_pilihBar;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JButton bt_tambahData;
    private javax.swing.JButton bt_tambahkan;
    private javax.swing.JComboBox<String> cbx_satuan;
    private javax.swing.JPanel dataBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_idUser;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton pilihSup;
    private javax.swing.JPanel pn_barang;
    private javax.swing.JPanel pn_detail;
    private javax.swing.JPanel pn_pesan;
    private javax.swing.JPanel pn_supplier;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTextField t_harga;
    private javax.swing.JTextField t_hargaJual;
    private javax.swing.JTextField t_idSup;
    private javax.swing.JTextField t_jumlah;
    private javax.swing.JTextField t_kodeBarang;
    private javax.swing.JTextField t_namaBarang;
    private javax.swing.JTextField t_namaSup;
    private javax.swing.JTextField t_noPesan;
    private javax.swing.JTextField t_subTotal;
    private javax.swing.JTextField t_tanggal;
    private javax.swing.JTextField t_totalPem;
    private javax.swing.JPanel tambahBarang;
    private javax.swing.JTable tblDetail;
    private javax.swing.JTable tblPemesanan;
    private javax.swing.JTable tbl_semPes;
    // End of variables declaration//GEN-END:variables

//    private void dataTable() {
//        dataBarang.setVisible(false);
//        tambahBarang.setVisible(true);
//        int row = tblPemesanan.getSelectedRow();
//        jLabel3.setText("Perbarui Data");
//        t_noPesan.setEnabled(false);
//        
//        t_noPesan.setText(tblPemesanan.getModel().getValueAt(row, 0).toString());
//        t_namaBarang.setText(tblPemesanan.getModel().getValueAt(row, 3).toString());
//        t_harga.setText(tblPemesanan.getModel().getValueAt(row, 5).toString());
//        
//        aktif();
//        
//        bt_simpan.setText("Perbarui");
//        bt_batal.setVisible(true);
//    }
    
    private void loadData() {
        bt_hapusData.setVisible(false);
        bt_batalData.setVisible(false);
        List<model_pemesanan> list = servicePem.getData();
        tblModelPem.setData(list);
    }
    
    private void loadDataSem() {
        List<sementara_pesan> list = serviceSem.getData();
        tblModelSem.setData(list);
    }
    
    private void bersihBarang() {
        t_kodeBarang.setText("");
        t_namaBarang.setText("");
        cbx_satuan.setSelectedItem("Pilih Satuan");
        t_harga.setText("");
        t_jumlah.setText("");
        t_subTotal.setText("");
    }
    
    private void setTanggal() {
        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        t_tanggal.setText(sdf.format(now));
        t_tanggal.setEnabled(false);
    }
    
    private void resetForm() {
        bt_simpan.requestFocus();
        bt_simpan.setText("Tambah");
        t_noPesan.setText("");
        t_namaBarang.setText("");
        t_harga.setText("");
        
    }
    
    private void tampilPanel() {
        mainPanel.removeAll();
        String id = lb_idUser.getText();
        mainPanel.add(new transaksi_pemesanan(id));
        lb_idUser.setText(id);
        mainPanel.repaint();
        mainPanel.revalidate();
    }
    
//    private void aktif() {
//        t_namaBarang.setEnabled(true);
//        t_harga.setEnabled(true);
//        
//    }
    
    private void simpanData() {
//        if(validasiInput() == true) {
            String no_pesan = t_noPesan.getText();
            String tgl_pesan = t_tanggal.getText();
            Long total_pesan = Long.parseLong(t_totalPem.getText());
            String id_supliyer = t_idSup.getText();
            String id_pengguna = lb_idUser.getText();
            String status = "Sedang di kirim";
            
            model_pengguna modPeng = new model_pengguna();
            model_supliyer modSup = new model_supliyer();
            model_barang modBar = new model_barang();
            model_pemesanan modPem = new model_pemesanan();
            model_detail_pemesanan modDetPem = new model_detail_pemesanan();

//          Simpan table pemesanan
            modPem.setNo_pesan(no_pesan);
            modPem.setTgl_pesan(tgl_pesan);
            modPem.setTotal_pesan(total_pesan);
            modSup.setId_supliyer(id_supliyer);
            modPeng.setId_pengguna(id_pengguna);
            modPem.setModel_pengguna_pem(modPeng);
            modPem.setModel_supliyer_pem(modSup);
            
//          Simpan table detail pemesanan
            modDetPem.setMod_pemesanan_detPem(modPem);
            modDetPem.setMod_barang_detPem(modBar);
            modDetPem.setStatus(status);

            servicePem.tambahData(modPem);
            serviceDet.tambahData(modDetPem);
            serviceDet.hapusSementara(modDetPem);
            tblModelPem.tambahData(modPem);
            
            loadData();
//            resetForm();
            tampilPanel();
            bt_simpan.setText("Tambah");
//        }
    }
    
    private void hapusData() {
        int index = tblPemesanan.getSelectedRow();
        if(index != -1) {
            model_pemesanan modPem = tblModelPem.getData(tblPemesanan.convertRowIndexToModel(index));
            servicePem.hapusData(modPem);
            tblModelPem.hapusData(index);
            loadData();
            tblDetail.setVisible(false);

        }
    }
    
    private void hapusDataDetail() {
        int index = tblDetail.getSelectedRow();
        if(index != -1) {
            model_detail_pemesanan modDetPem = tblModelDet.getData(tblDetail.convertRowIndexToModel(index));
            if(JOptionPane.showConfirmDialog(null, "Yakin data ingin dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                serviceDet.hapusData(modDetPem);
                tblModelDet.hapusData(index);
                loadData();
                tblDetail.setVisible(false);
//                resetForm();
            } else {
                JOptionPane.showMessageDialog(null, "Pilih dahulu data yang akan dihapus");
            }
            
        }
        
    }
    
    
    private void tambahDataSementara() {
        String kode_barang = t_kodeBarang.getText();
        String nama_barang = t_namaBarang.getText();
        Long hargaBeli = Long.parseLong(t_harga.getText());
        Long hargaJual = Long.parseLong(t_hargaJual.getText());
        
        sementara_pesan semPes = new sementara_pesan();
        model_barang modBar = new model_barang();
        
        modBar.setKode_barang(kode_barang);
        modBar.setNama_barang(nama_barang);  
        modBar.setHarga(hargaBeli);
        semPes.setMdl_brg(modBar);
        
        if(serviceSem.validasiNamaBarang(semPes)==true) {  
            if(validasiInput()==true) {
                if(serviceSem.validasiHarga(semPes, hargaJual)) {          
        String kode = t_kodeBarang.getText();
        String nama = t_namaBarang.getText();
        String satuan = cbx_satuan.getSelectedItem().toString();
        Long harga = Long.parseLong(t_harga.getText());
        Integer jumlah = Integer.parseInt(t_jumlah.getText());
        Long sub_total = Long.parseLong(t_subTotal.getText());
        String status = "Sedang Dikirim";
        
        model_barang mb = new model_barang();
        model_detail_pemesanan mdp = new model_detail_pemesanan();
        sementara_pesan sp = new sementara_pesan();
        
        mb.setKode_barang(kode);
        mb.setNama_barang(nama);
        mb.setSatuan(satuan);
        mb.setHarga(harga);
        
        mdp.setJml_pesan(jumlah);
        mdp.setSubtotal_pesan(sub_total);
        Long subtotal = mdp.getSubtotal_pesan();
        mdp.setSubtotal_pesan(subtotal);
        mdp.setStatus(status);
        
        sp.setMdl_brg(mb);
        sp.setMdl_mdp(mdp);
        
        serviceSem.tambahData(sp);
        serviceDet.sumTotal(mdp);
        t_totalPem.setText(mdp.getSubtotal_pesan().toString());
        if(JOptionPane.showConfirmDialog(this, "Mau Tambah barang?", "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        bersihBarang();
        
        } else {
        bersihBarang();
        }
        
        loadDataSem();
            }
        }
      }
    }
    
    private void perbaruiDataSementara() {
        int index = tbl_semPes.getSelectedRow();
        if(index != -1) {
            sementara_pesan semenPes = tblModelSem.getData(tbl_semPes.convertRowIndexToModel(index));
            
            if(validasiInput() == true) {
            String kode_barang = t_kodeBarang.getText();
            String nama_barang = t_namaBarang.getText();
            String satuan = cbx_satuan.getSelectedItem().toString();
            Long harga = Long.parseLong(t_harga.getText());
            Integer jumlah = Integer.parseInt(t_jumlah.getText());
            Long subTotal = Long.parseLong(t_subTotal.getText());
            String status = "Sedang dikirim";
            
            model_barang mb = new model_barang();
            model_detail_pemesanan mdp = new model_detail_pemesanan();
            sementara_pesan sp = new sementara_pesan();
            
            mb.setKode_barang(kode_barang);
            mb.setNama_barang(nama_barang);
            mb.setSatuan(satuan);
            mb.setHarga(harga);
            mdp.setJml_pesan(jumlah);
            mdp.setSubtotal_pesan(subTotal);
            mdp.setStatus(status);
            
            sp.setMdl_brg(mb);
            sp.setMdl_mdp(mdp);
            
            serviceSem.perbaruiData(sp);
            serviceDet.sumTotal(mdp);
            tblModelSem.perbaruiData(index, sp);
            t_totalPem.setText(mdp.getSubtotal_pesan().toString());
            
            bt_tambahkan.setText("Tambahkan");
            bt_tambahkan.setBackground(new Color(0,11,109));
            bt_batalkan.setVisible(false);
            bt_hapuskan.setVisible(false);
            
            loadDataSem();
            bersihBarang();
        }
    }
}
        private void hapusDataSementara() {
        int index = tbl_semPes.getSelectedRow();
        if(index != -1) {
            sementara_pesan semPes = tblModelSem.getData(tbl_semPes.convertRowIndexToModel(index));
            if(JOptionPane.showConfirmDialog(null, "Yakin data ingin dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                model_detail_pemesanan mdp = new model_detail_pemesanan();
                Long subTotal = Long.parseLong(t_subTotal.getText());
                mdp.setSubtotal_pesan(subTotal);

                serviceSem.hapusData(semPes);
                serviceDet.sumTotal(mdp);
                tblModelSem.hapusData(index);
                t_totalPem.setText(mdp.getSubtotal_pesan().toString());
                
                bt_tambahkan.setText("Tambahkan");
                bt_tambahkan.setBackground(new Color(0,11,109));
                bt_batalkan.setVisible(false);
                bt_hapuskan.setVisible(false);
                loadDataSem();
                bersihBarang();
//                resetForm();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu data dahulu yang akan dihapus");
        }
    }
    
    private void pencarian() {
        int row = tblPemesanan.getSelectedRow();
        String no_pesan = tblPemesanan.getValueAt(row, 0).toString();
        List<model_detail_pemesanan> list = serviceDet.pencarian(t_cari.getText(), no_pesan);
        tblModelDet.setData(list);
    }
    
    private boolean validasiInput() {
        boolean valid = false;
        if(t_idSup.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID Supplier tidak boleh kosong");
        } 
          else if(t_kodeBarang.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Barang tidak boleh kosong");
        }
          else if(cbx_satuan.getSelectedItem().equals("Pilih Satuan")) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih satuan");
        } else if(t_harga.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harga tidak boleh kosong");
        } else if(t_jumlah.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Jumlah tidak boleh kosong");
        } else {
            valid = true;
        }
        return valid;
    }
    
    static public class HeaderColor extends DefaultTableCellRenderer{

        public HeaderColor() {
            setOpaque(true);
        }
        
        public Component getTableCellRendererComponent(JTable tbl_contoh, Object value, boolean selected, boolean focused, int row, int column) {
            super.getTableCellRendererComponent(tbl_contoh, value, selected, focused, row, column);
            setBackground(new Color(0,139,185,255));
            setForeground(new Color(255, 255, 255));
            setFont(new Font(null, Font.BOLD, 18));
            return this;
        }
    
    }
    
}
