package view_transaksi;
import control.Control_barang;
import control.Control_barangKeluar;
import control.Control_detBarangKeluar;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import java.awt.Color;
import control.Control_semKeluar;
import crud.Crud_Barang;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.model_barang;
import model.model_pengguna;
import model.model_supliyer;
import model.model_barangKeluar;
import model.model_detail_barangKeluar;
import model.sementara_keluar;
import crud.trans_barangKeluar;
import crud.trans_detBarangKeluar;
import crud.trans_semKeluar;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import model.model_detail_barangKeluar;
import tableModel.tm_barangKeluar;
import tableModel.tm_detBarangKeluar;
import tableModel.tm_semKeluar;


public class transaksi_barangKeluar extends javax.swing.JPanel {
    private Control_barangKeluar serviceKel = new trans_barangKeluar();
    private Control_detBarangKeluar serviceDet = new trans_detBarangKeluar();
    private Control_semKeluar serviceSem = new trans_semKeluar();
    
    private tm_barangKeluar tblModelKel = new tm_barangKeluar();
    private tm_detBarangKeluar tblModelDet = new tm_detBarangKeluar();
    private tm_semKeluar tblModelSem = new tm_semKeluar();
    
    public transaksi_barangKeluar(String id) {
        initComponents();
        lb_idUser.setText(id);
        tblBarangKel.getTableHeader().setDefaultRenderer(new HeaderColor());
        tblDetail.getTableHeader().setDefaultRenderer(new HeaderColor());
        tbl_semKeluar.getTableHeader().setDefaultRenderer(new HeaderColor());
        tblBarangKel.setRowHeight(50);
        tblDetail.setRowHeight(50);
        tbl_semKeluar.setRowHeight(50);
        tblBarangKel.setModel(tblModelKel);
        tblDetail.setModel(tblModelDet);
        tbl_semKeluar.setModel(tblModelSem);
        pn_detail.setVisible(false);
        
        loadData();
        loadDataSem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel3 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        dataBarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_tambahData = new javax.swing.JButton();
        bt_hapusData = new javax.swing.JButton();
        bt_batalData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarangKel = new javax.swing.JTable();
        t_cari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pn_detail = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDetail = new javax.swing.JTable();
        bt_closeDet = new javax.swing.JButton();
        lb_idUser = new javax.swing.JLabel();
        tambahBarang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bt_simpan = new javax.swing.JButton();
        bt_batal = new javax.swing.JButton();
        pn_pesan = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        t_noKeluar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        t_tanggal = new javax.swing.JTextField();
        pn_barang = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        t_kodeBarang = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        t_namaBarang = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bt_pilihBar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        t_harga = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        t_jumlah = new javax.swing.JTextField();
        t_subTotal = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cbx_satuan = new javax.swing.JComboBox<>();
        bt_tambahkan = new javax.swing.JButton();
        bt_batalkan = new javax.swing.JButton();
        bt_hapuskan = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        cbx_keterangan = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_semKeluar = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t_totalKel = new javax.swing.JTextField();
        t_qty = new javax.swing.JTextField();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataBarang.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("Transaksi Barang Keluar");

        bt_tambahData.setBackground(new java.awt.Color(0, 11, 109));
        bt_tambahData.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_tambahData.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahData.setText("Tambah");
        bt_tambahData.setBorderPainted(false);
        bt_tambahData.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_tambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahDataActionPerformed(evt);
            }
        });

        bt_hapusData.setBackground(new java.awt.Color(255, 0, 0));
        bt_hapusData.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_hapusData.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusData.setText("Hapus");
        bt_hapusData.setBorderPainted(false);
        bt_hapusData.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_hapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusDataActionPerformed(evt);
            }
        });

        bt_batalData.setBackground(new java.awt.Color(255, 102, 0));
        bt_batalData.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_batalData.setForeground(new java.awt.Color(255, 255, 255));
        bt_batalData.setText("Batal");
        bt_batalData.setBorderPainted(false);
        bt_batalData.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_batalData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalDataActionPerformed(evt);
            }
        });

        tblBarangKel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tblBarangKel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarangKel.setGridColor(new java.awt.Color(204, 204, 204));
        tblBarangKel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangKelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarangKel);

        t_cari.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        t_cari.setForeground(new java.awt.Color(153, 153, 153));
        t_cari.setText("Cari");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_cari.setPreferredSize(new java.awt.Dimension(30, 20));
        t_cari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_cariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_cariFocusLost(evt);
            }
        });
        t_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cariActionPerformed(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_cariKeyReleased(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/magnifying-glass.png"))); // NOI18N

        pn_detail.setBackground(new java.awt.Color(0, 11, 109));
        pn_detail.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Detail Transaksi");

        tblDetail.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetail.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(tblDetail);

        bt_closeDet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/closeMenu.png"))); // NOI18N
        bt_closeDet.setContentAreaFilled(false);
        bt_closeDet.setOpaque(true);
        bt_closeDet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_closeDetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_closeDetMouseExited(evt);
            }
        });
        bt_closeDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_closeDetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_detailLayout = new javax.swing.GroupLayout(pn_detail);
        pn_detail.setLayout(pn_detailLayout);
        pn_detailLayout.setHorizontalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_closeDet)
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1153, Short.MAX_VALUE)
        );
        pn_detailLayout.setVerticalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(bt_closeDet))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
        );

        lb_idUser.setBackground(new java.awt.Color(255, 255, 255));
        lb_idUser.setForeground(new java.awt.Color(255, 255, 255));
        lb_idUser.setText("ID USER");

        javax.swing.GroupLayout dataBarangLayout = new javax.swing.GroupLayout(dataBarang);
        dataBarang.setLayout(dataBarangLayout);
        dataBarangLayout.setHorizontalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addComponent(bt_tambahData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_hapusData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_batalData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(681, 681, 681)))
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_idUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_cari, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1153, Short.MAX_VALUE)
            .addComponent(pn_detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dataBarangLayout.setVerticalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lb_idUser))
                .addGap(18, 18, 18)
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_tambahData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_hapusData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_batalData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(dataBarang, "card2");

        tambahBarang.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel3.setText("Tambah Transaksi Barang Keluar");

        bt_simpan.setBackground(new java.awt.Color(0, 11, 109));
        bt_simpan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_simpan.setForeground(new java.awt.Color(255, 255, 255));
        bt_simpan.setText("Simpan");
        bt_simpan.setBorderPainted(false);
        bt_simpan.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpanActionPerformed(evt);
            }
        });

        bt_batal.setBackground(new java.awt.Color(252, 102, 0));
        bt_batal.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_batal.setForeground(new java.awt.Color(255, 255, 255));
        bt_batal.setText("Batal");
        bt_batal.setBorderPainted(false);
        bt_batal.setPreferredSize(new java.awt.Dimension(100, 50));
        bt_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalActionPerformed(evt);
            }
        });

        pn_pesan.setBackground(new java.awt.Color(255, 255, 255));
        pn_pesan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setText("No Keluar");

        t_noKeluar.setBackground(new java.awt.Color(255, 255, 255));
        t_noKeluar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_noKeluar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_noKeluar.setPreferredSize(new java.awt.Dimension(1, 30));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel15.setText("Tahun/Bulan/Tanggal");

        t_tanggal.setBackground(new java.awt.Color(255, 255, 255));
        t_tanggal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        t_tanggal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_tanggal.setPreferredSize(new java.awt.Dimension(1, 30));

        javax.swing.GroupLayout pn_pesanLayout = new javax.swing.GroupLayout(pn_pesan);
        pn_pesan.setLayout(pn_pesanLayout);
        pn_pesanLayout.setHorizontalGroup(
            pn_pesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pesanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_pesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_pesanLayout.createSequentialGroup()
                        .addGroup(pn_pesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(t_tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_noKeluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_pesanLayout.setVerticalGroup(
            pn_pesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pesanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_noKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(t_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pn_barang.setBackground(new java.awt.Color(255, 255, 255));
        pn_barang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel20.setText("Kode Barang");

        t_kodeBarang.setBackground(new java.awt.Color(255, 255, 255));
        t_kodeBarang.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_kodeBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_kodeBarang.setPreferredSize(new java.awt.Dimension(1, 30));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel21.setText("Nama Barang");

        t_namaBarang.setBackground(new java.awt.Color(255, 255, 255));
        t_namaBarang.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_namaBarang.setForeground(new java.awt.Color(0, 0, 0));
        t_namaBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_namaBarang.setPreferredSize(new java.awt.Dimension(1, 30));

        jPanel2.setBackground(new java.awt.Color(0, 11, 109));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Barang");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        bt_pilihBar.setBackground(new java.awt.Color(0, 11, 109));
        bt_pilihBar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        bt_pilihBar.setForeground(new java.awt.Color(255, 255, 255));
        bt_pilihBar.setText("Pilih");
        bt_pilihBar.setPreferredSize(new java.awt.Dimension(75, 35));
        bt_pilihBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pilihBarActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel22.setText("Satuan");

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel23.setText("Harga");

        t_harga.setBackground(new java.awt.Color(255, 255, 255));
        t_harga.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_harga.setForeground(new java.awt.Color(0, 0, 0));
        t_harga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_harga.setPreferredSize(new java.awt.Dimension(1, 30));
        t_harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_hargaKeyPressed(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel24.setText("Jumlah");

        t_jumlah.setBackground(new java.awt.Color(255, 255, 255));
        t_jumlah.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_jumlah.setForeground(new java.awt.Color(0, 0, 0));
        t_jumlah.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_jumlah.setPreferredSize(new java.awt.Dimension(1, 30));
        t_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_jumlahKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_jumlahKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_jumlahKeyTyped(evt);
            }
        });

        t_subTotal.setBackground(new java.awt.Color(255, 255, 255));
        t_subTotal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        t_subTotal.setForeground(new java.awt.Color(0, 0, 0));
        t_subTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_subTotal.setPreferredSize(new java.awt.Dimension(1, 30));

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel25.setText("Subtotal");

        cbx_satuan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cbx_satuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Satuan", "Pcs", "Pack" }));
        cbx_satuan.setMinimumSize(new java.awt.Dimension(120, 30));

        bt_tambahkan.setBackground(new java.awt.Color(0, 11, 109));
        bt_tambahkan.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        bt_tambahkan.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahkan.setText("Tambahkan");
        bt_tambahkan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_tambahkan.setPreferredSize(new java.awt.Dimension(175, 26));
        bt_tambahkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahkanActionPerformed(evt);
            }
        });

        bt_batalkan.setBackground(new java.awt.Color(252, 102, 0));
        bt_batalkan.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        bt_batalkan.setForeground(new java.awt.Color(255, 255, 255));
        bt_batalkan.setText("Batal");
        bt_batalkan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_batalkan.setPreferredSize(new java.awt.Dimension(175, 26));
        bt_batalkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_batalkanActionPerformed(evt);
            }
        });

        bt_hapuskan.setBackground(new java.awt.Color(255, 0, 0));
        bt_hapuskan.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        bt_hapuskan.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapuskan.setText("Hapus");
        bt_hapuskan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_hapuskan.setPreferredSize(new java.awt.Dimension(175, 26));
        bt_hapuskan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapuskanActionPerformed(evt);
            }
        });

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel26.setText("Keterangan");

        cbx_keterangan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cbx_keterangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terjual", "Rusak" }));
        cbx_keterangan.setPreferredSize(new java.awt.Dimension(83, 30));

        javax.swing.GroupLayout pn_barangLayout = new javax.swing.GroupLayout(pn_barang);
        pn_barang.setLayout(pn_barangLayout);
        pn_barangLayout.setHorizontalGroup(
            pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_barangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_barangLayout.createSequentialGroup()
                        .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_namaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pn_barangLayout.createSequentialGroup()
                                .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addGap(0, 263, Short.MAX_VALUE))
                            .addGroup(pn_barangLayout.createSequentialGroup()
                                .addComponent(t_kodeBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_pilihBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_barangLayout.createSequentialGroup()
                        .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_hapuskan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_batalkan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_tambahkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_barangLayout.createSequentialGroup()
                        .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbx_keterangan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_harga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_jumlah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_subTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_barangLayout.createSequentialGroup()
                                .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cbx_satuan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        pn_barangLayout.setVerticalGroup(
            pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_barangLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_kodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_pilihBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_tambahkan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_batalkan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_hapuskan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_semKeluar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tbl_semKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_semKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_semKeluarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_semKeluar);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("TOTAL KELUAR");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Rp");

        t_totalKel.setBackground(new java.awt.Color(255, 255, 255));
        t_totalKel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        t_totalKel.setForeground(new java.awt.Color(0, 0, 0));
        t_totalKel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t_totalKel.setText(".......");
        t_totalKel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_totalKel.setPreferredSize(new java.awt.Dimension(50, 30));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_totalKel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(t_totalKel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        t_qty.setForeground(new java.awt.Color(0, 0, 0));
        t_qty.setText("jTextField1");

        javax.swing.GroupLayout tambahBarangLayout = new javax.swing.GroupLayout(tambahBarang);
        tambahBarang.setLayout(tambahBarangLayout);
        tambahBarangLayout.setHorizontalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahBarangLayout.createSequentialGroup()
                        .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pn_barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pn_pesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(t_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(tambahBarangLayout.createSequentialGroup()
                        .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(tambahBarangLayout.createSequentialGroup()
                                .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        tambahBarangLayout.setVerticalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_batal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahBarangLayout.createSequentialGroup()
                        .addComponent(pn_pesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(t_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(tambahBarangLayout.createSequentialGroup()
                        .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahBarangLayout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(tambahBarangLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jScrollPane2)))
                        .addContainerGap())))
        );

        mainPanel.add(tambahBarang, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_hapusDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusDataActionPerformed
//        hapusDataDetail();
//        bt_tambahData.setText("Tambah");

    }//GEN-LAST:event_bt_hapusDataActionPerformed

    private void bt_batalDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalDataActionPerformed
        loadData();
        tampilPanel();
    }//GEN-LAST:event_bt_batalDataActionPerformed

    private void bt_tambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahDataActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(tambahBarang);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        t_noKeluar.setText(serviceKel.nomor());
        t_noKeluar.setEnabled(false);
        setTanggal();
        t_kodeBarang.setEnabled(false);
        t_namaBarang.setEnabled(false);
        t_harga.setEnabled(false);
        t_subTotal.setEnabled(false);
        bt_batalkan.setVisible(false);
        bt_hapuskan.setVisible(false);
        t_qty.setVisible(false);
        
        model_detail_barangKeluar mdbk = new model_detail_barangKeluar();
        Long subtotal = mdbk.getSubtotal_keluar();
        mdbk.setSubtotal_keluar(subtotal);
        serviceDet.sumTotal(mdbk);
        t_totalKel.setText(String.valueOf(mdbk.getSubtotal_keluar()));
        
        loadDataSem();
//        if(bt_tambahData.getText().equalsIgnoreCase("Ubah")) {
//            dataTable();
//        }
        
    }//GEN-LAST:event_bt_tambahDataActionPerformed

    private void bt_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalActionPerformed
        loadData();
        tampilPanel();
        resetForm();
    }//GEN-LAST:event_bt_batalActionPerformed

    private void tblBarangKelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangKelMouseClicked
          int row = tblBarangKel.getSelectedRow();
          String id = tblBarangKel.getValueAt(row, 0).toString();
          
//          bt_hapusData.setVisible(true);
//          bt_batalData.setVisible(true);
          pn_detail.setVisible(true);
          bt_closeDet.setBackground(null);
          List<model_detail_barangKeluar> list = serviceDet.getData(id);
          tblModelDet.setData(list);
    }//GEN-LAST:event_tblBarangKelMouseClicked

    private void bt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpanActionPerformed
       if(bt_simpan.getText().equalsIgnoreCase("Simpan")) {
           simpanData();
       } else if(bt_simpan.getText().equals("Perbarui")) {
//           perbaruiData();
       }
           
    }//GEN-LAST:event_bt_simpanActionPerformed

    private void t_cariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_cariFocusGained
        if(t_cari.getText().equalsIgnoreCase("Cari")) {
            t_cari.setText("");
            t_cari.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_t_cariFocusGained

    private void t_cariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_cariFocusLost
        if(t_cari.getText().equalsIgnoreCase("")) {
            t_cari.setText("Cari");
        }
    }//GEN-LAST:event_t_cariFocusLost

    private void t_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyReleased
        pencarian();
    }//GEN-LAST:event_t_cariKeyReleased

    private void bt_closeDetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_closeDetMouseEntered
        bt_closeDet.setBackground(Color.red);
    }//GEN-LAST:event_bt_closeDetMouseEntered

    private void bt_closeDetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_closeDetMouseExited
        bt_closeDet.setBackground(null);
    }//GEN-LAST:event_bt_closeDetMouseExited

    private void bt_closeDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_closeDetActionPerformed
        pn_detail.setVisible(false);
    }//GEN-LAST:event_bt_closeDetActionPerformed

    private void bt_pilihBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pilihBarActionPerformed
        boolean closeable = true;
        dialog_barang db = new dialog_barang(null, closeable);
        db.setVisible(true);
        
        t_kodeBarang.setText(db.Barang.getKode_barang());
        t_namaBarang.setText(db.Barang.getNama_barang());
        cbx_satuan.setSelectedItem(db.Barang.getSatuan());
        t_harga.setText(db.Barang.getHarga().toString());
        t_qty.setText(db.Barang.getStok().toString());
        t_jumlah.requestFocus();
   
    }//GEN-LAST:event_bt_pilihBarActionPerformed

    private void t_hargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_hargaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_jumlah.requestFocus();
        }
    }//GEN-LAST:event_t_hargaKeyPressed

    private void bt_tambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahkanActionPerformed
        if(bt_tambahkan.getText().equals("Tambahkan")) {
            tambahDataSementara();
        } else if(bt_tambahkan.getText().equals("Perbarui")) {
            perbaruiDataSementara();
        }
    }//GEN-LAST:event_bt_tambahkanActionPerformed

    private void tbl_semKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_semKeluarMouseClicked
        int row = tbl_semKeluar.getSelectedRow();
        
        t_kodeBarang.setText(tbl_semKeluar.getModel().getValueAt(row, 0).toString());
        t_namaBarang.setText(tbl_semKeluar.getModel().getValueAt(row, 1).toString());
        cbx_satuan.setSelectedItem(tbl_semKeluar.getModel().getValueAt(row, 2).toString());
        t_harga.setText(tbl_semKeluar.getModel().getValueAt(row, 3).toString());
        t_jumlah.setText(tbl_semKeluar.getModel().getValueAt(row, 4).toString());
        t_subTotal.setText(tbl_semKeluar.getModel().getValueAt(row, 5).toString());
        
        bt_tambahkan.setText("Perbarui");
        bt_tambahkan.setBackground(new Color(51, 102, 0));
        bt_batalkan.setVisible(true);
        bt_hapuskan.setVisible(true);
        
    }//GEN-LAST:event_tbl_semKeluarMouseClicked

    private void bt_batalkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_batalkanActionPerformed
        loadDataSem();
        bersihBarang();
        bt_tambahkan.setText("Tambahkan");
        bt_tambahkan.setBackground(new Color(0, 11, 109));
        bt_batalkan.setVisible(false);
        bt_hapuskan.setVisible(false);
    }//GEN-LAST:event_bt_batalkanActionPerformed

    private void bt_hapuskanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapuskanActionPerformed
        hapusDataSementara();
    }//GEN-LAST:event_bt_hapuskanActionPerformed

    private void t_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_jumlahKeyReleased
            long harga = Integer.parseInt(t_harga.getText());
            int jumlah;
            String inputJumlah = t_jumlah.getText();
            
            if(inputJumlah.isEmpty()) {
                jumlah = 0;
            } else {
                jumlah = Integer.parseInt(inputJumlah);
            }
            
            long subTotal = jumlah * harga;
            t_subTotal.setText(Long.toString(subTotal));
            

    }//GEN-LAST:event_t_jumlahKeyReleased

    private void t_jumlahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_jumlahKeyPressed
//       if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
//           bt_tambahkanActionPerformed(new ActionEvent(evt.getSource(), evt.getID(), null));
//       }
    }//GEN-LAST:event_t_jumlahKeyPressed

    private void t_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_cariActionPerformed

    private void t_jumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_jumlahKeyTyped
        char enter = evt.getKeyChar();
        if(Character.isDigit(enter) == false) {
        evt.consume();  
        }
    }//GEN-LAST:event_t_jumlahKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_batal;
    private javax.swing.JButton bt_batalData;
    private javax.swing.JButton bt_batalkan;
    private javax.swing.JButton bt_closeDet;
    private javax.swing.JButton bt_hapusData;
    private javax.swing.JButton bt_hapuskan;
    private javax.swing.JButton bt_pilihBar;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JButton bt_tambahData;
    private javax.swing.JButton bt_tambahkan;
    private javax.swing.JComboBox<String> cbx_keterangan;
    private javax.swing.JComboBox<String> cbx_satuan;
    private javax.swing.JPanel dataBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_idUser;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_barang;
    private javax.swing.JPanel pn_detail;
    private javax.swing.JPanel pn_pesan;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTextField t_harga;
    private javax.swing.JTextField t_jumlah;
    private javax.swing.JTextField t_kodeBarang;
    private javax.swing.JTextField t_namaBarang;
    private javax.swing.JTextField t_noKeluar;
    private javax.swing.JTextField t_qty;
    private javax.swing.JTextField t_subTotal;
    private javax.swing.JTextField t_tanggal;
    private javax.swing.JTextField t_totalKel;
    private javax.swing.JPanel tambahBarang;
    private javax.swing.JTable tblBarangKel;
    private javax.swing.JTable tblDetail;
    private javax.swing.JTable tbl_semKeluar;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        bt_hapusData.setVisible(false);
        bt_batalData.setVisible(false);
        List<model_barangKeluar> list = serviceKel.getData();
        tblModelKel.setData(list);
    }
    
    private void loadDataSem() {
        List<sementara_keluar> list = serviceSem.getData();
        tblModelSem.setData(list);
    }
    
    private void bersihBarang() {
        t_kodeBarang.setText("");
        t_namaBarang.setText("");
        cbx_satuan.setSelectedItem("Pilih Satuan");
        t_harga.setText("");
        t_jumlah.setText("");
        t_subTotal.setText("");
    }
    
    private void setTanggal() {
        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        t_tanggal.setText(sdf.format(now));
        t_tanggal.setEnabled(false);
    }
    
    private void resetForm() {
        bt_simpan.requestFocus();
        bt_simpan.setText("Tambah");
        t_noKeluar.setText("");
        t_namaBarang.setText("");
        t_harga.setText("");
        
    }
    
    private void tampilPanel() {
        mainPanel.removeAll();
        String id = lb_idUser.getText();
        mainPanel.add(new transaksi_barangKeluar(id));
        lb_idUser.setText(id);
        mainPanel.repaint();
        mainPanel.revalidate();
    }
    
    
    private void simpanData() {
//        if(validasiInput() == true) {
            String no_keluar = t_noKeluar.getText();
            String tgl_keluar = t_tanggal.getText();
            Long total_keluar = Long.parseLong(t_totalKel.getText());
            String id_pengguna = lb_idUser.getText();
            String keterangan = cbx_keterangan.getSelectedItem().toString();
            
            model_pengguna modPeng = new model_pengguna();
            model_barang modBar = new model_barang();
            model_barangKeluar modKel = new model_barangKeluar();
            model_detail_barangKeluar modDetKel = new model_detail_barangKeluar();

//          Simpan table pemesanan
            modKel.setNo_keluar(no_keluar);
            modKel.setTgl_keluar(tgl_keluar);
            modKel.setTotal_keluar(total_keluar);
            modPeng.setId_pengguna(id_pengguna);
            modKel.setMod_pengguna(modPeng);
            
//          Simpan table detail pemesanan
            modDetKel.setMod_barangKel_detKel(modKel);
            modDetKel.setMod_barang_detKel(modBar);
            modDetKel.setKeterangan(keterangan);
            
            
            
            serviceKel.tambahData(modKel);
            serviceDet.tambahData(modDetKel);
            serviceDet.hapusSementara(modDetKel);
            tblModelKel.tambahData(modKel);
            loadData();
//            resetForm();
            tampilPanel();
            bt_simpan.setText("Tambah");
//        }
    }
    
//    private void hapusData() {
//        int index = tblBarangKel.getSelectedRow();
//        if(index != -1) {
//            model_barangKeluar modKel = tblModelKel.getData(tblBarangKel.convertRowIndexToModel(index));
//            serviceKel.hapusData(modKel);
//            tblModelKel.hapusData(index);
//            loadData();
//            tblDetail.setVisible(false);
//
//        }
//    }
    
//    private void hapusDataDetail() {
//        int index = tblDetail.getSelectedRow();
//        if(index != -1) {
//            model_detail_barangKeluar modDetKel = tblModelDet.getData(tblDetail.convertRowIndexToModel(index));
//            if(JOptionPane.showConfirmDialog(null, "Yakin data ingin dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
//                serviceDet.hapusData(modDetKel);
//                tblModelDet.hapusData(index);
//                loadData();
//                tblDetail.setVisible(false);
////                resetForm();
//            } else {
//                JOptionPane.showMessageDialog(null, "Pilih dahulu data yang akan dihapus");
//            }
//            
//        }
//        
//    }
    
    
    private void tambahDataSementara() {
        if(validasiInput() == true) {
        Control_barang serviceBar = new Crud_Barang();
        model_barang brg = new model_barang();
        brg.setStok(Integer.parseInt(t_qty.getText()));
        
        int qty = Integer.parseInt(t_jumlah.getText());
   
        if(serviceBar.validasiQtyStok(brg, qty)) {
            
        String kodeKel = t_kodeBarang.getText();
        String namaKel = t_namaBarang.getText();
        String satuanKel = cbx_satuan.getSelectedItem().toString();
        Long hargaKel = Long.parseLong(t_harga.getText());
        Integer jumlahKel = Integer.parseInt(t_jumlah.getText());
        Long subtotal_Kel = Long.parseLong(t_subTotal.getText());
        String ketKel = cbx_keterangan.getSelectedItem().toString();
        
        model_barang mb = new model_barang();
        model_detail_barangKeluar mdbk = new model_detail_barangKeluar();
        sementara_keluar sk = new sementara_keluar();
        
        mb.setKode_barang(kodeKel);
        mb.setNama_barang(namaKel);
        mb.setSatuan(satuanKel);
        mb.setHarga(hargaKel);
        
        mdbk.setJml_keluar(jumlahKel);
        mdbk.setSubtotal_keluar(subtotal_Kel);
        Long subKel = mdbk.getSubtotal_keluar();
        mdbk.setSubtotal_keluar(subKel);
        mdbk.setKeterangan(ketKel);
        
        sk.setMdl_brg(mb);
        sk.setMdl_mdbk(mdbk);
        
        serviceSem.tambahData(sk);
        serviceDet.sumTotal(mdbk);
        t_totalKel.setText(mdbk.getSubtotal_keluar().toString());
        if(JOptionPane.showConfirmDialog(this, "Mau Tambah barang?", "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        bersihBarang();
        } else {
        bersihBarang();
        }
        
        loadDataSem();
        
        }
        }
        
    }
    
    private void perbaruiDataSementara() {
        int row = tbl_semKeluar.getSelectedRow();
        int index = tbl_semKeluar.getSelectedRow();
//        if(index != -1) {
//            sementara_keluar semenKel = tblModelSem.getData(tbl_semKeluar.convertRowIndexToModel(index));
            sementara_keluar semKel = new sementara_keluar();
            model_barang brg = new model_barang();
            model_detail_barangKeluar mod_detBar = new model_detail_barangKeluar();
            
            brg.setKode_barang(tbl_semKeluar.getModel().getValueAt(row, 0).toString());
            brg.setNama_barang(tbl_semKeluar.getModel().getValueAt(row, 1).toString());
            brg.setSatuan(tbl_semKeluar.getModel().getValueAt(row, 2).toString());
            brg.setHarga(Long.parseLong(tbl_semKeluar.getModel().getValueAt(row, 3).toString()));
            mod_detBar.setJml_keluar(Integer.parseInt(tbl_semKeluar.getModel().getValueAt(row, 4).toString()));
            mod_detBar.setSubtotal_keluar(Long.parseLong(tbl_semKeluar.getModel().getValueAt(row, 5).toString()));
            
            semKel.setMdl_brg(brg);
            semKel.setMdl_mdbk(mod_detBar);
            semKel.setKeterangan(tbl_semKeluar.getModel().getValueAt(row, 6).toString());
            
            if(validasiInput() == true) {
            String kode_barang = t_kodeBarang.getText();
            String nama_barang = t_namaBarang.getText();
            String satuan = cbx_satuan.getSelectedItem().toString();
            Long harga = Long.parseLong(t_harga.getText());
            Integer jumlah = Integer.parseInt(t_jumlah.getText());
            Long subTotal = Long.parseLong(t_subTotal.getText());
            String keterangan = cbx_keterangan.getSelectedItem().toString();
            
            model_barang mb = new model_barang();
            model_detail_barangKeluar mdbk = new model_detail_barangKeluar();
            sementara_keluar sk = new sementara_keluar();
            
            mb.setKode_barang(kode_barang);
            mb.setNama_barang(nama_barang);
            mb.setSatuan(satuan);
            mb.setHarga(harga);
            mdbk.setJml_keluar(jumlah);
            mdbk.setSubtotal_keluar(subTotal);
            
            sk.setMdl_brg(mb);
            sk.setMdl_mdbk(mdbk);
            sk.setKeterangan(keterangan);
            
            serviceSem.perbaruiData(sk, semKel);
            serviceDet.sumTotal(mdbk);
            tblModelSem.perbaruiData(index, sk);
            t_totalKel.setText(mdbk.getSubtotal_keluar().toString());
            
            bt_tambahkan.setText("Tambahkan");
            bt_tambahkan.setBackground(new Color(0,11,109));
            bt_batalkan.setVisible(false);
            bt_hapuskan.setVisible(false);
            
            loadDataSem();
            bersihBarang();
        }
//    }
}
        private void hapusDataSementara() {
        int row = tbl_semKeluar.getSelectedRow();
        int index = tbl_semKeluar.getSelectedRow();
//        if(index != -1) {
//            sementara_keluar semKel = tblModelSem.getData(tbl_semKeluar.convertRowIndexToModel(index));
            sementara_keluar semKel = new sementara_keluar();
            model_barang brg = new model_barang();
            model_detail_barangKeluar mod_detBar = new model_detail_barangKeluar();
            
            brg.setKode_barang(tbl_semKeluar.getModel().getValueAt(row, 0).toString());
            brg.setNama_barang(tbl_semKeluar.getModel().getValueAt(row, 1).toString());
            brg.setSatuan(tbl_semKeluar.getModel().getValueAt(row, 2).toString());
            brg.setHarga(Long.parseLong(tbl_semKeluar.getModel().getValueAt(row, 3).toString()));
            mod_detBar.setJml_keluar(Integer.parseInt(tbl_semKeluar.getModel().getValueAt(row, 4).toString()));
            mod_detBar.setSubtotal_keluar(Long.parseLong(tbl_semKeluar.getModel().getValueAt(row, 5).toString()));
            
            semKel.setMdl_brg(brg);
            semKel.setMdl_mdbk(mod_detBar);
            semKel.setKeterangan(tbl_semKeluar.getModel().getValueAt(row, 6).toString());
            if(JOptionPane.showConfirmDialog(null, "Yakin data ingin dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                model_detail_barangKeluar mdbk = new model_detail_barangKeluar();
                Long subTotal = Long.parseLong(t_subTotal.getText());
                mdbk.setSubtotal_keluar(subTotal);

                serviceSem.hapusData(semKel);
                serviceDet.sumTotal(mdbk);
                tblModelSem.hapusData(index);
                t_totalKel.setText(mdbk.getSubtotal_keluar().toString());
                
                bt_tambahkan.setText("Tambahkan");
                bt_tambahkan.setBackground(new Color(0,11,109));
                bt_batalkan.setVisible(false);
                bt_hapuskan.setVisible(false);
                loadDataSem();
                bersihBarang();
//                resetForm();
            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Pilih dahulu data dahulu yang akan dihapus");
//        }
    }
    
    private void pencarian() {
        int row = tblBarangKel.getSelectedRow();
        String no_keluar = tblBarangKel.getValueAt(row, 0).toString();
        List<model_detail_barangKeluar> list = serviceDet.pencarian(t_cari.getText(), no_keluar);
        tblModelDet.setData(list);
    }
    
    private boolean validasiInput() {
        boolean valid = false;
        if(t_kodeBarang.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Barang tidak boleh kosong");
        } 
        else if(cbx_satuan.getSelectedItem().equals("Pilih Satuan")) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih satuan");
        } else if(t_jumlah.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Jumlah tidak boleh kosong");
        } else if(cbx_keterangan.getSelectedItem().equals(null)) {
            JOptionPane.showMessageDialog(null, "Keterangan tidak boleh kosong");
        }
        
        else {
            valid = true;
        }
        return valid;
    }
    
    static public class HeaderColor extends DefaultTableCellRenderer{

        public HeaderColor() {
            setOpaque(true);
        }
        
        public Component getTableCellRendererComponent(JTable tbl_contoh, Object value, boolean selected, boolean focused, int row, int column) {
            super.getTableCellRendererComponent(tbl_contoh, value, selected, focused, row, column);
            setBackground(new Color(0,139,185,255));
            setForeground(new Color(255, 255, 255));
            setFont(new Font(null, Font.BOLD, 18));
            return this;
        }
    
    }
    
}
